-- ==============================================================
-- Generated by Vitis HLS v2023.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Fast_processor_txPath is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_continue : IN STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    time_from_book_TVALID : IN STD_LOGIC;
    metadata_from_book_TVALID : IN STD_LOGIC;
    lbTxMetadataOut_TREADY : IN STD_LOGIC;
    order_from_book_TVALID : IN STD_LOGIC;
    lbTxDataOut_TREADY : IN STD_LOGIC;
    lbTxLengthOut_TREADY : IN STD_LOGIC;
    tagsOut_TREADY : IN STD_LOGIC;
    metadata_from_book_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    metadata_from_book_TREADY : OUT STD_LOGIC;
    lbTxDataOut_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    lbTxDataOut_TVALID : OUT STD_LOGIC;
    lbTxMetadataOut_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    lbTxMetadataOut_TVALID : OUT STD_LOGIC;
    lbTxLengthOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    lbTxLengthOut_TVALID : OUT STD_LOGIC;
    time_from_book_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    time_from_book_TREADY : OUT STD_LOGIC;
    tagsOut_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    tagsOut_TVALID : OUT STD_LOGIC;
    order_from_book_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
    order_from_book_TREADY : OUT STD_LOGIC );
end;


architecture behav of Fast_processor_txPath is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_iter0_fsm_state1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_ST_iter0_fsm_state2 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_ST_iter0_fsm_state3 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_ST_iter1_fsm_state4 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_iter1_fsm_state5 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_ST_iter0_fsm_state6 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_ST_iter1_fsm_state0 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv2_2 : STD_LOGIC_VECTOR (1 downto 0) := "10";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv128_lc_2 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000111111110000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv16_80 : STD_LOGIC_VECTOR (15 downto 0) := "0000000010000000";
    constant ap_const_lv72_0 : STD_LOGIC_VECTOR (71 downto 0) := "000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv73_FF0000000000000000 : STD_LOGIC_VECTOR (72 downto 0) := "0111111110000000000000000000000000000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_iter0_fsm : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    signal ap_CS_iter0_fsm_state1 : STD_LOGIC;
    signal ap_CS_iter1_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    signal ap_CS_iter1_fsm_state0 : STD_LOGIC;
    signal ap_CS_iter0_fsm_state3 : STD_LOGIC;
    signal next_state_load_reg_232 : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_reg_236 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_240 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_244 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_279 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_248 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_nbwritereq_fu_116_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op37_read_state3 : BOOLEAN;
    signal ap_predicate_op38_read_state3 : BOOLEAN;
    signal ap_predicate_op39_write_state3 : BOOLEAN;
    signal ap_predicate_op40_read_state3 : BOOLEAN;
    signal ap_block_state3_pp0_stage3_iter0 : BOOLEAN;
    signal ap_block_state3_io : BOOLEAN;
    signal next_state_load_reg_232_pp0_iter0_reg : STD_LOGIC_VECTOR (1 downto 0);
    signal tmp_1_reg_252 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op43_write_state4 : BOOLEAN;
    signal tmp_2_reg_256 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op48_write_state4 : BOOLEAN;
    signal ap_predicate_op49_write_state4 : BOOLEAN;
    signal tmp_reg_236_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_reg_240_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_reg_244_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_5_reg_279_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_6_reg_248_pp0_iter0_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_7_reg_260 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_predicate_op50_write_state4 : BOOLEAN;
    signal ap_predicate_op51_write_state4 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state4 : STD_LOGIC;
    signal ap_predicate_op52_write_state5 : BOOLEAN;
    signal ap_predicate_op55_write_state5 : BOOLEAN;
    signal ap_predicate_op56_write_state5 : BOOLEAN;
    signal ap_predicate_op59_write_state5 : BOOLEAN;
    signal regslice_both_lbTxDataOut_U_apdone_blk : STD_LOGIC;
    signal regslice_both_lbTxMetadataOut_U_apdone_blk : STD_LOGIC;
    signal regslice_both_lbTxLengthOut_U_apdone_blk : STD_LOGIC;
    signal regslice_both_tagsOut_U_apdone_blk : STD_LOGIC;
    signal ap_block_state5_pp0_stage1_iter1 : BOOLEAN;
    signal ap_block_state5_io : BOOLEAN;
    signal ap_CS_iter1_fsm_state5 : STD_LOGIC;
    signal ap_done_reg : STD_LOGIC := '0';
    signal next_state : STD_LOGIC_VECTOR (1 downto 0) := "00";
    signal second_packet_last : STD_LOGIC_VECTOR (0 downto 0) := "0";
    signal metadata_from_book_TDATA_blk_n : STD_LOGIC;
    signal lbTxDataOut_TDATA_blk_n : STD_LOGIC;
    signal lbTxMetadataOut_TDATA_blk_n : STD_LOGIC;
    signal lbTxLengthOut_TDATA_blk_n : STD_LOGIC;
    signal time_from_book_TDATA_blk_n : STD_LOGIC;
    signal tagsOut_TDATA_blk_n : STD_LOGIC;
    signal order_from_book_TDATA_blk_n : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal tmp_nbreadreq_fu_76_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_3_nbreadreq_fu_84_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_nbreadreq_fu_92_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_iter0_fsm_state2 : STD_LOGIC;
    signal grp_nbwritereq_fu_108_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal time_from_book_read_reg_264 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln215_fu_227_p1 : STD_LOGIC_VECTOR (127 downto 0);
    signal ap_CS_iter0_fsm_state6 : STD_LOGIC;
    signal shl_ln_fu_213_p3 : STD_LOGIC_VECTOR (72 downto 0);
    signal or_ln215_fu_221_p2 : STD_LOGIC_VECTOR (72 downto 0);
    signal ap_NS_iter0_fsm : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_iter1_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_ST_iter0_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_iter0_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_iter0_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_iter1_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_iter0_fsm_state6_blk : STD_LOGIC;
    signal regslice_both_metadata_from_book_U_apdone_blk : STD_LOGIC;
    signal metadata_from_book_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal metadata_from_book_TVALID_int_regslice : STD_LOGIC;
    signal metadata_from_book_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_metadata_from_book_U_ack_in : STD_LOGIC;
    signal lbTxDataOut_TDATA_int_regslice : STD_LOGIC_VECTOR (127 downto 0);
    signal lbTxDataOut_TVALID_int_regslice : STD_LOGIC;
    signal lbTxDataOut_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_lbTxDataOut_U_vld_out : STD_LOGIC;
    signal lbTxMetadataOut_TVALID_int_regslice : STD_LOGIC;
    signal lbTxMetadataOut_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_lbTxMetadataOut_U_vld_out : STD_LOGIC;
    signal lbTxLengthOut_TVALID_int_regslice : STD_LOGIC;
    signal lbTxLengthOut_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_lbTxLengthOut_U_vld_out : STD_LOGIC;
    signal regslice_both_time_from_book_U_apdone_blk : STD_LOGIC;
    signal time_from_book_TDATA_int_regslice : STD_LOGIC_VECTOR (63 downto 0);
    signal time_from_book_TVALID_int_regslice : STD_LOGIC;
    signal time_from_book_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_time_from_book_U_ack_in : STD_LOGIC;
    signal tagsOut_TVALID_int_regslice : STD_LOGIC;
    signal tagsOut_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_tagsOut_U_vld_out : STD_LOGIC;
    signal regslice_both_order_from_book_U_apdone_blk : STD_LOGIC;
    signal order_from_book_TDATA_int_regslice : STD_LOGIC_VECTOR (95 downto 0);
    signal order_from_book_TVALID_int_regslice : STD_LOGIC;
    signal order_from_book_TREADY_int_regslice : STD_LOGIC;
    signal regslice_both_order_from_book_U_ack_in : STD_LOGIC;
    signal ap_condition_332 : BOOLEAN;
    signal ap_condition_68 : BOOLEAN;
    signal ap_condition_208 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component Fast_processor_regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_metadata_from_book_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => metadata_from_book_TDATA,
        vld_in => metadata_from_book_TVALID,
        ack_in => regslice_both_metadata_from_book_U_ack_in,
        data_out => metadata_from_book_TDATA_int_regslice,
        vld_out => metadata_from_book_TVALID_int_regslice,
        ack_out => metadata_from_book_TREADY_int_regslice,
        apdone_blk => regslice_both_metadata_from_book_U_apdone_blk);

    regslice_both_lbTxDataOut_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => lbTxDataOut_TDATA_int_regslice,
        vld_in => lbTxDataOut_TVALID_int_regslice,
        ack_in => lbTxDataOut_TREADY_int_regslice,
        data_out => lbTxDataOut_TDATA,
        vld_out => regslice_both_lbTxDataOut_U_vld_out,
        ack_out => lbTxDataOut_TREADY,
        apdone_blk => regslice_both_lbTxDataOut_U_apdone_blk);

    regslice_both_lbTxMetadataOut_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 128)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => metadata_from_book_TDATA_int_regslice,
        vld_in => lbTxMetadataOut_TVALID_int_regslice,
        ack_in => lbTxMetadataOut_TREADY_int_regslice,
        data_out => lbTxMetadataOut_TDATA,
        vld_out => regslice_both_lbTxMetadataOut_U_vld_out,
        ack_out => lbTxMetadataOut_TREADY,
        apdone_blk => regslice_both_lbTxMetadataOut_U_apdone_blk);

    regslice_both_lbTxLengthOut_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 16)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => ap_const_lv16_80,
        vld_in => lbTxLengthOut_TVALID_int_regslice,
        ack_in => lbTxLengthOut_TREADY_int_regslice,
        data_out => lbTxLengthOut_TDATA,
        vld_out => regslice_both_lbTxLengthOut_U_vld_out,
        ack_out => lbTxLengthOut_TREADY,
        apdone_blk => regslice_both_lbTxLengthOut_U_apdone_blk);

    regslice_both_time_from_book_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => time_from_book_TDATA,
        vld_in => time_from_book_TVALID,
        ack_in => regslice_both_time_from_book_U_ack_in,
        data_out => time_from_book_TDATA_int_regslice,
        vld_out => time_from_book_TVALID_int_regslice,
        ack_out => time_from_book_TREADY_int_regslice,
        apdone_blk => regslice_both_time_from_book_U_apdone_blk);

    regslice_both_tagsOut_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 64)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => time_from_book_read_reg_264,
        vld_in => tagsOut_TVALID_int_regslice,
        ack_in => tagsOut_TREADY_int_regslice,
        data_out => tagsOut_TDATA,
        vld_out => regslice_both_tagsOut_U_vld_out,
        ack_out => tagsOut_TREADY,
        apdone_blk => regslice_both_tagsOut_U_apdone_blk);

    regslice_both_order_from_book_U : component Fast_processor_regslice_both
    generic map (
        DataWidth => 96)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        data_in => order_from_book_TDATA,
        vld_in => order_from_book_TVALID,
        ack_in => regslice_both_order_from_book_U_ack_in,
        data_out => order_from_book_TDATA_int_regslice,
        vld_out => order_from_book_TVALID_int_regslice,
        ack_out => order_from_book_TREADY_int_regslice,
        apdone_blk => regslice_both_order_from_book_U_apdone_blk);





    ap_CS_iter0_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
            else
                ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
            end if;
        end if;
    end process;


    ap_CS_iter1_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
            else
                ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state5))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    next_state_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_208)) then
                if ((ap_const_boolean_1 = ap_condition_68)) then 
                    next_state <= ap_const_lv2_1;
                elsif (((next_state_load_reg_232 = ap_const_lv2_2) and (grp_nbwritereq_fu_108_p3 = ap_const_lv1_1))) then 
                    next_state <= ap_const_lv2_0;
                elsif (((next_state_load_reg_232 = ap_const_lv2_1) and (grp_nbwritereq_fu_108_p3 = ap_const_lv1_1))) then 
                    next_state <= ap_const_lv2_2;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                next_state_load_reg_232 <= next_state;
                tmp_3_reg_240 <= tmp_3_nbreadreq_fu_84_p3;
                tmp_4_reg_244 <= tmp_4_nbreadreq_fu_92_p3;
                tmp_reg_236 <= tmp_nbreadreq_fu_76_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then
                next_state_load_reg_232_pp0_iter0_reg <= next_state_load_reg_232;
                time_from_book_read_reg_264 <= time_from_book_TDATA_int_regslice;
                tmp_1_reg_252 <= (0=>lbTxDataOut_TREADY_int_regslice, others=>'-');
                tmp_2_reg_256 <= (0=>lbTxDataOut_TREADY_int_regslice, others=>'-');
                tmp_3_reg_240_pp0_iter0_reg <= tmp_3_reg_240;
                tmp_4_reg_244_pp0_iter0_reg <= tmp_4_reg_244;
                tmp_5_reg_279_pp0_iter0_reg <= tmp_5_reg_279;
                tmp_6_reg_248_pp0_iter0_reg <= tmp_6_reg_248;
                tmp_7_reg_260 <= (0=>tagsOut_TREADY_int_regslice, others=>'-');
                tmp_reg_236_pp0_iter0_reg <= tmp_reg_236;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not((next_state_load_reg_232 = ap_const_lv2_1)) and not((next_state_load_reg_232 = ap_const_lv2_2)) and not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (grp_nbwritereq_fu_116_p3 = ap_const_lv1_1) and (tmp_6_reg_248 = ap_const_lv1_1) and (tmp_5_reg_279 = ap_const_lv1_1) and (tmp_4_reg_244 = ap_const_lv1_1) and (tmp_3_reg_240 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then
                second_packet_last <= ap_const_lv1_1;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state6))) then
                tmp_5_reg_279 <= (0=>lbTxMetadataOut_TREADY_int_regslice, others=>'-');
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                tmp_6_reg_248 <= (0=>lbTxLengthOut_TREADY_int_regslice, others=>'-');
            end if;
        end if;
    end process;

    ap_NS_iter0_fsm_assign_proc : process (ap_CS_iter0_fsm, ap_CS_iter0_fsm_state1, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg, ap_block_state1_pp0_stage0_iter0, ap_CS_iter0_fsm_state2, ap_CS_iter0_fsm_state6)
    begin
        case ap_CS_iter0_fsm is
            when ap_ST_iter0_fsm_state1 => 
                if ((not(((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1))) then
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state6;
                else
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
                end if;
            when ap_ST_iter0_fsm_state2 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state2))) then
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state3;
                else
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state2;
                end if;
            when ap_ST_iter0_fsm_state3 => 
                if (not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1)))))) then
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state1;
                else
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state3;
                end if;
            when ap_ST_iter0_fsm_state6 => 
                if ((not(((ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state6))) then
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state2;
                else
                    ap_NS_iter0_fsm <= ap_ST_iter0_fsm_state6;
                end if;
            when others =>  
                ap_NS_iter0_fsm <= "XXXX";
        end case;
    end process;

    ap_NS_iter1_fsm_assign_proc : process (ap_CS_iter1_fsm, ap_CS_iter0_fsm_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        case ap_CS_iter1_fsm is
            when ap_ST_iter1_fsm_state4 => 
                if ((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state4))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state5;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state4;
                end if;
            when ap_ST_iter1_fsm_state5 => 
                if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0))) and not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state4;
                elsif ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1) or (ap_done_reg = ap_const_logic_1))) and ((ap_const_logic_0 = ap_CS_iter0_fsm_state3) or ((ap_const_logic_1 = ap_CS_iter0_fsm_state3) and ((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0)))))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state5;
                end if;
            when ap_ST_iter1_fsm_state0 => 
                if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state4;
                else
                    ap_NS_iter1_fsm <= ap_ST_iter1_fsm_state0;
                end if;
            when others =>  
                ap_NS_iter1_fsm <= "XXX";
        end case;
    end process;
    ap_CS_iter0_fsm_state1 <= ap_CS_iter0_fsm(0);
    ap_CS_iter0_fsm_state2 <= ap_CS_iter0_fsm(2);
    ap_CS_iter0_fsm_state3 <= ap_CS_iter0_fsm(3);
    ap_CS_iter0_fsm_state6 <= ap_CS_iter0_fsm(1);
    ap_CS_iter1_fsm_state0 <= ap_CS_iter1_fsm(0);
    ap_CS_iter1_fsm_state4 <= ap_CS_iter1_fsm(1);
    ap_CS_iter1_fsm_state5 <= ap_CS_iter1_fsm(2);

    ap_ST_iter0_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_iter0_fsm_state2_blk <= ap_const_logic_0;

    ap_ST_iter0_fsm_state3_blk_assign_proc : process(ap_block_state3_pp0_stage3_iter0, ap_block_state3_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0))) then 
            ap_ST_iter0_fsm_state3_blk <= ap_const_logic_1;
        else 
            ap_ST_iter0_fsm_state3_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_iter0_fsm_state6_blk <= ap_const_logic_0;

    ap_ST_iter1_fsm_state4_blk_assign_proc : process(ap_block_state4_pp0_stage0_iter1, ap_block_state4_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))) then 
            ap_ST_iter1_fsm_state4_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state4_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_iter1_fsm_state5_blk_assign_proc : process(ap_block_state5_pp0_stage1_iter1, ap_block_state5_io)
    begin
        if (((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) then 
            ap_ST_iter1_fsm_state5_blk <= ap_const_logic_1;
        else 
            ap_ST_iter1_fsm_state5_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start, ap_done_reg)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_done_reg = ap_const_logic_1) or (ap_start = ap_const_logic_0));
    end process;


    ap_block_state3_io_assign_proc : process(ap_predicate_op39_write_state3, lbTxMetadataOut_TREADY_int_regslice)
    begin
                ap_block_state3_io <= ((ap_predicate_op39_write_state3 = ap_const_boolean_1) and (lbTxMetadataOut_TREADY_int_regslice = ap_const_logic_0));
    end process;


    ap_block_state3_pp0_stage3_iter0_assign_proc : process(ap_predicate_op37_read_state3, ap_predicate_op38_read_state3, ap_predicate_op39_write_state3, ap_predicate_op40_read_state3, metadata_from_book_TVALID_int_regslice, lbTxMetadataOut_TREADY_int_regslice, time_from_book_TVALID_int_regslice, order_from_book_TVALID_int_regslice)
    begin
                ap_block_state3_pp0_stage3_iter0 <= (((ap_predicate_op40_read_state3 = ap_const_boolean_1) and (order_from_book_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op39_write_state3 = ap_const_boolean_1) and (lbTxMetadataOut_TREADY_int_regslice = ap_const_logic_0)) or ((ap_predicate_op38_read_state3 = ap_const_boolean_1) and (metadata_from_book_TVALID_int_regslice = ap_const_logic_0)) or ((ap_predicate_op37_read_state3 = ap_const_boolean_1) and (time_from_book_TVALID_int_regslice = ap_const_logic_0)));
    end process;


    ap_block_state4_io_assign_proc : process(ap_predicate_op43_write_state4, ap_predicate_op48_write_state4, ap_predicate_op49_write_state4, ap_predicate_op50_write_state4, ap_predicate_op51_write_state4, lbTxDataOut_TREADY_int_regslice, lbTxMetadataOut_TREADY_int_regslice, lbTxLengthOut_TREADY_int_regslice, tagsOut_TREADY_int_regslice)
    begin
                ap_block_state4_io <= (((tagsOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op50_write_state4 = ap_const_boolean_1)) or ((lbTxLengthOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op49_write_state4 = ap_const_boolean_1)) or ((lbTxMetadataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op51_write_state4 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op48_write_state4 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op43_write_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state4_pp0_stage0_iter1_assign_proc : process(ap_predicate_op43_write_state4, ap_predicate_op48_write_state4, ap_predicate_op49_write_state4, ap_predicate_op50_write_state4, ap_predicate_op51_write_state4, lbTxDataOut_TREADY_int_regslice, lbTxMetadataOut_TREADY_int_regslice, lbTxLengthOut_TREADY_int_regslice, tagsOut_TREADY_int_regslice)
    begin
                ap_block_state4_pp0_stage0_iter1 <= (((tagsOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op50_write_state4 = ap_const_boolean_1)) or ((lbTxLengthOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op49_write_state4 = ap_const_boolean_1)) or ((lbTxMetadataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op51_write_state4 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op48_write_state4 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op43_write_state4 = ap_const_boolean_1)));
    end process;


    ap_block_state5_io_assign_proc : process(ap_predicate_op52_write_state5, ap_predicate_op55_write_state5, ap_predicate_op56_write_state5, ap_predicate_op59_write_state5, lbTxDataOut_TREADY_int_regslice, lbTxLengthOut_TREADY_int_regslice, tagsOut_TREADY_int_regslice)
    begin
                ap_block_state5_io <= (((tagsOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op59_write_state5 = ap_const_boolean_1)) or ((lbTxLengthOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op56_write_state5 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op55_write_state5 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op52_write_state5 = ap_const_boolean_1)));
    end process;


    ap_block_state5_pp0_stage1_iter1_assign_proc : process(ap_predicate_op52_write_state5, ap_predicate_op55_write_state5, ap_predicate_op56_write_state5, ap_predicate_op59_write_state5, regslice_both_lbTxDataOut_U_apdone_blk, regslice_both_lbTxMetadataOut_U_apdone_blk, regslice_both_lbTxLengthOut_U_apdone_blk, regslice_both_tagsOut_U_apdone_blk, lbTxDataOut_TREADY_int_regslice, lbTxLengthOut_TREADY_int_regslice, tagsOut_TREADY_int_regslice)
    begin
                ap_block_state5_pp0_stage1_iter1 <= ((regslice_both_tagsOut_U_apdone_blk = ap_const_logic_1) or (regslice_both_lbTxLengthOut_U_apdone_blk = ap_const_logic_1) or (regslice_both_lbTxMetadataOut_U_apdone_blk = ap_const_logic_1) or (regslice_both_lbTxDataOut_U_apdone_blk = ap_const_logic_1) or ((tagsOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op59_write_state5 = ap_const_boolean_1)) or ((lbTxLengthOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op56_write_state5 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op55_write_state5 = ap_const_boolean_1)) or ((lbTxDataOut_TREADY_int_regslice = ap_const_logic_0) and (ap_predicate_op52_write_state5 = ap_const_boolean_1)));
    end process;


    ap_condition_208_assign_proc : process(ap_CS_iter0_fsm_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
                ap_condition_208 <= (not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3));
    end process;


    ap_condition_332_assign_proc : process(ap_block_state4_pp0_stage0_iter1, ap_CS_iter1_fsm_state4, ap_done_reg)
    begin
                ap_condition_332 <= (not(((ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state4));
    end process;


    ap_condition_68_assign_proc : process(next_state_load_reg_232, tmp_reg_236, tmp_3_reg_240, tmp_4_reg_244, tmp_5_reg_279, tmp_6_reg_248, grp_nbwritereq_fu_116_p3)
    begin
                ap_condition_68 <= (not((next_state_load_reg_232 = ap_const_lv2_1)) and not((next_state_load_reg_232 = ap_const_lv2_2)) and (grp_nbwritereq_fu_116_p3 = ap_const_lv1_1) and (tmp_6_reg_248 = ap_const_lv1_1) and (tmp_5_reg_279 = ap_const_lv1_1) and (tmp_4_reg_244 = ap_const_lv1_1) and (tmp_3_reg_240 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_1));
    end process;


    ap_done_assign_proc : process(ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state5))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_iter0_fsm_state1, ap_CS_iter1_fsm_state0)
    begin
        if (((ap_const_logic_1 = ap_CS_iter1_fsm_state0) and (ap_const_logic_1 = ap_CS_iter0_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_predicate_op37_read_state3_assign_proc : process(next_state_load_reg_232, tmp_reg_236, tmp_3_reg_240, tmp_4_reg_244, tmp_5_reg_279, tmp_6_reg_248, grp_nbwritereq_fu_116_p3)
    begin
                ap_predicate_op37_read_state3 <= (not((next_state_load_reg_232 = ap_const_lv2_1)) and not((next_state_load_reg_232 = ap_const_lv2_2)) and (grp_nbwritereq_fu_116_p3 = ap_const_lv1_1) and (tmp_6_reg_248 = ap_const_lv1_1) and (tmp_5_reg_279 = ap_const_lv1_1) and (tmp_4_reg_244 = ap_const_lv1_1) and (tmp_3_reg_240 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_1));
    end process;


    ap_predicate_op38_read_state3_assign_proc : process(next_state_load_reg_232, tmp_reg_236, tmp_3_reg_240, tmp_4_reg_244, tmp_5_reg_279, tmp_6_reg_248, grp_nbwritereq_fu_116_p3)
    begin
                ap_predicate_op38_read_state3 <= (not((next_state_load_reg_232 = ap_const_lv2_1)) and not((next_state_load_reg_232 = ap_const_lv2_2)) and (grp_nbwritereq_fu_116_p3 = ap_const_lv1_1) and (tmp_6_reg_248 = ap_const_lv1_1) and (tmp_5_reg_279 = ap_const_lv1_1) and (tmp_4_reg_244 = ap_const_lv1_1) and (tmp_3_reg_240 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_1));
    end process;


    ap_predicate_op39_write_state3_assign_proc : process(next_state_load_reg_232, tmp_reg_236, tmp_3_reg_240, tmp_4_reg_244, tmp_5_reg_279, tmp_6_reg_248, grp_nbwritereq_fu_116_p3)
    begin
                ap_predicate_op39_write_state3 <= (not((next_state_load_reg_232 = ap_const_lv2_1)) and not((next_state_load_reg_232 = ap_const_lv2_2)) and (grp_nbwritereq_fu_116_p3 = ap_const_lv1_1) and (tmp_6_reg_248 = ap_const_lv1_1) and (tmp_5_reg_279 = ap_const_lv1_1) and (tmp_4_reg_244 = ap_const_lv1_1) and (tmp_3_reg_240 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_1));
    end process;


    ap_predicate_op40_read_state3_assign_proc : process(next_state_load_reg_232, tmp_reg_236, tmp_3_reg_240, tmp_4_reg_244, tmp_5_reg_279, tmp_6_reg_248, grp_nbwritereq_fu_116_p3)
    begin
                ap_predicate_op40_read_state3 <= (not((next_state_load_reg_232 = ap_const_lv2_1)) and not((next_state_load_reg_232 = ap_const_lv2_2)) and (grp_nbwritereq_fu_116_p3 = ap_const_lv1_1) and (tmp_6_reg_248 = ap_const_lv1_1) and (tmp_5_reg_279 = ap_const_lv1_1) and (tmp_4_reg_244 = ap_const_lv1_1) and (tmp_3_reg_240 = ap_const_lv1_1) and (tmp_reg_236 = ap_const_lv1_1));
    end process;


    ap_predicate_op43_write_state4_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_1_reg_252)
    begin
                ap_predicate_op43_write_state4 <= ((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_1) and (tmp_1_reg_252 = ap_const_lv1_1));
    end process;


    ap_predicate_op48_write_state4_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_2_reg_256)
    begin
                ap_predicate_op48_write_state4 <= ((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2) and (tmp_2_reg_256 = ap_const_lv1_1));
    end process;


    ap_predicate_op49_write_state4_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_2_reg_256)
    begin
                ap_predicate_op49_write_state4 <= ((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2) and (tmp_2_reg_256 = ap_const_lv1_1));
    end process;


    ap_predicate_op50_write_state4_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_reg_236_pp0_iter0_reg, tmp_3_reg_240_pp0_iter0_reg, tmp_4_reg_244_pp0_iter0_reg, tmp_5_reg_279_pp0_iter0_reg, tmp_6_reg_248_pp0_iter0_reg, tmp_7_reg_260)
    begin
                ap_predicate_op50_write_state4 <= (not((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_1)) and not((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2)) and (tmp_7_reg_260 = ap_const_lv1_1) and (tmp_6_reg_248_pp0_iter0_reg = ap_const_lv1_1) and (tmp_5_reg_279_pp0_iter0_reg = ap_const_lv1_1) and (tmp_4_reg_244_pp0_iter0_reg = ap_const_lv1_1) and (tmp_3_reg_240_pp0_iter0_reg = ap_const_lv1_1) and (tmp_reg_236_pp0_iter0_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op51_write_state4_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_reg_236_pp0_iter0_reg, tmp_3_reg_240_pp0_iter0_reg, tmp_4_reg_244_pp0_iter0_reg, tmp_5_reg_279_pp0_iter0_reg, tmp_6_reg_248_pp0_iter0_reg, tmp_7_reg_260)
    begin
                ap_predicate_op51_write_state4 <= (not((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_1)) and not((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2)) and (tmp_7_reg_260 = ap_const_lv1_1) and (tmp_6_reg_248_pp0_iter0_reg = ap_const_lv1_1) and (tmp_5_reg_279_pp0_iter0_reg = ap_const_lv1_1) and (tmp_4_reg_244_pp0_iter0_reg = ap_const_lv1_1) and (tmp_3_reg_240_pp0_iter0_reg = ap_const_lv1_1) and (tmp_reg_236_pp0_iter0_reg = ap_const_lv1_1));
    end process;


    ap_predicate_op52_write_state5_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_1_reg_252)
    begin
                ap_predicate_op52_write_state5 <= ((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_1) and (tmp_1_reg_252 = ap_const_lv1_1));
    end process;


    ap_predicate_op55_write_state5_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_2_reg_256)
    begin
                ap_predicate_op55_write_state5 <= ((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2) and (tmp_2_reg_256 = ap_const_lv1_1));
    end process;


    ap_predicate_op56_write_state5_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_2_reg_256)
    begin
                ap_predicate_op56_write_state5 <= ((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2) and (tmp_2_reg_256 = ap_const_lv1_1));
    end process;


    ap_predicate_op59_write_state5_assign_proc : process(next_state_load_reg_232_pp0_iter0_reg, tmp_reg_236_pp0_iter0_reg, tmp_3_reg_240_pp0_iter0_reg, tmp_4_reg_244_pp0_iter0_reg, tmp_5_reg_279_pp0_iter0_reg, tmp_6_reg_248_pp0_iter0_reg, tmp_7_reg_260)
    begin
                ap_predicate_op59_write_state5 <= (not((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_1)) and not((next_state_load_reg_232_pp0_iter0_reg = ap_const_lv2_2)) and (tmp_7_reg_260 = ap_const_lv1_1) and (tmp_6_reg_248_pp0_iter0_reg = ap_const_lv1_1) and (tmp_5_reg_279_pp0_iter0_reg = ap_const_lv1_1) and (tmp_4_reg_244_pp0_iter0_reg = ap_const_lv1_1) and (tmp_3_reg_240_pp0_iter0_reg = ap_const_lv1_1) and (tmp_reg_236_pp0_iter0_reg = ap_const_lv1_1));
    end process;


    ap_ready_assign_proc : process(ap_CS_iter0_fsm_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_nbwritereq_fu_108_p3 <= (0=>lbTxDataOut_TREADY_int_regslice, others=>'-');
    grp_nbwritereq_fu_116_p3 <= (0=>tagsOut_TREADY_int_regslice, others=>'-');

    lbTxDataOut_TDATA_blk_n_assign_proc : process(ap_predicate_op43_write_state4, ap_predicate_op48_write_state4, ap_CS_iter1_fsm_state4, ap_predicate_op52_write_state5, ap_predicate_op55_write_state5, ap_CS_iter1_fsm_state5, lbTxDataOut_TREADY_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and (ap_predicate_op55_write_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and (ap_predicate_op52_write_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op48_write_state4 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op43_write_state4 = ap_const_boolean_1)))) then 
            lbTxDataOut_TDATA_blk_n <= lbTxDataOut_TREADY_int_regslice;
        else 
            lbTxDataOut_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    lbTxDataOut_TDATA_int_regslice_assign_proc : process(ap_predicate_op43_write_state4, ap_predicate_op48_write_state4, zext_ln215_fu_227_p1, ap_condition_332)
    begin
        if ((ap_const_boolean_1 = ap_condition_332)) then
            if ((ap_predicate_op48_write_state4 = ap_const_boolean_1)) then 
                lbTxDataOut_TDATA_int_regslice <= zext_ln215_fu_227_p1;
            elsif ((ap_predicate_op43_write_state4 = ap_const_boolean_1)) then 
                lbTxDataOut_TDATA_int_regslice <= ap_const_lv128_lc_2;
            else 
                lbTxDataOut_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
            end if;
        else 
            lbTxDataOut_TDATA_int_regslice <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;

    lbTxDataOut_TVALID <= regslice_both_lbTxDataOut_U_vld_out;

    lbTxDataOut_TVALID_int_regslice_assign_proc : process(ap_predicate_op43_write_state4, ap_predicate_op48_write_state4, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_done_reg)
    begin
        if (((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op48_write_state4 = ap_const_boolean_1)) or (not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op43_write_state4 = ap_const_boolean_1)))) then 
            lbTxDataOut_TVALID_int_regslice <= ap_const_logic_1;
        else 
            lbTxDataOut_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    lbTxLengthOut_TDATA_blk_n_assign_proc : process(ap_predicate_op49_write_state4, ap_CS_iter1_fsm_state4, ap_predicate_op56_write_state5, ap_CS_iter1_fsm_state5, lbTxLengthOut_TREADY_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and (ap_predicate_op56_write_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op49_write_state4 = ap_const_boolean_1)))) then 
            lbTxLengthOut_TDATA_blk_n <= lbTxLengthOut_TREADY_int_regslice;
        else 
            lbTxLengthOut_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lbTxLengthOut_TVALID <= regslice_both_lbTxLengthOut_U_vld_out;

    lbTxLengthOut_TVALID_int_regslice_assign_proc : process(ap_predicate_op49_write_state4, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op49_write_state4 = ap_const_boolean_1))) then 
            lbTxLengthOut_TVALID_int_regslice <= ap_const_logic_1;
        else 
            lbTxLengthOut_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    lbTxMetadataOut_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op39_write_state3, ap_predicate_op51_write_state4, ap_CS_iter1_fsm_state4, lbTxMetadataOut_TREADY_int_regslice)
    begin
        if ((((ap_predicate_op39_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op51_write_state4 = ap_const_boolean_1)))) then 
            lbTxMetadataOut_TDATA_blk_n <= lbTxMetadataOut_TREADY_int_regslice;
        else 
            lbTxMetadataOut_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    lbTxMetadataOut_TVALID <= regslice_both_lbTxMetadataOut_U_vld_out;

    lbTxMetadataOut_TVALID_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op39_write_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_predicate_op39_write_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            lbTxMetadataOut_TVALID_int_regslice <= ap_const_logic_1;
        else 
            lbTxMetadataOut_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    metadata_from_book_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op38_read_state3, metadata_from_book_TVALID_int_regslice)
    begin
        if (((ap_predicate_op38_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            metadata_from_book_TDATA_blk_n <= metadata_from_book_TVALID_int_regslice;
        else 
            metadata_from_book_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    metadata_from_book_TREADY <= regslice_both_metadata_from_book_U_ack_in;

    metadata_from_book_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op38_read_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_predicate_op38_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            metadata_from_book_TREADY_int_regslice <= ap_const_logic_1;
        else 
            metadata_from_book_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    or_ln215_fu_221_p2 <= (shl_ln_fu_213_p3 or ap_const_lv73_FF0000000000000000);

    order_from_book_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op40_read_state3, order_from_book_TVALID_int_regslice)
    begin
        if (((ap_predicate_op40_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            order_from_book_TDATA_blk_n <= order_from_book_TVALID_int_regslice;
        else 
            order_from_book_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    order_from_book_TREADY <= regslice_both_order_from_book_U_ack_in;

    order_from_book_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op40_read_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_predicate_op40_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            order_from_book_TREADY_int_regslice <= ap_const_logic_1;
        else 
            order_from_book_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    shl_ln_fu_213_p3 <= (second_packet_last & ap_const_lv72_0);

    tagsOut_TDATA_blk_n_assign_proc : process(ap_predicate_op50_write_state4, ap_CS_iter1_fsm_state4, ap_predicate_op59_write_state5, ap_CS_iter1_fsm_state5, tagsOut_TREADY_int_regslice)
    begin
        if ((((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and (ap_predicate_op59_write_state5 = ap_const_boolean_1)) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op50_write_state4 = ap_const_boolean_1)))) then 
            tagsOut_TDATA_blk_n <= tagsOut_TREADY_int_regslice;
        else 
            tagsOut_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    tagsOut_TVALID <= regslice_both_tagsOut_U_vld_out;

    tagsOut_TVALID_int_regslice_assign_proc : process(ap_predicate_op50_write_state4, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1) or (ap_done_reg = ap_const_logic_1))) and (ap_const_logic_1 = ap_CS_iter1_fsm_state4) and (ap_predicate_op50_write_state4 = ap_const_boolean_1))) then 
            tagsOut_TVALID_int_regslice <= ap_const_logic_1;
        else 
            tagsOut_TVALID_int_regslice <= ap_const_logic_0;
        end if; 
    end process;


    time_from_book_TDATA_blk_n_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op37_read_state3, time_from_book_TVALID_int_regslice)
    begin
        if (((ap_predicate_op37_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            time_from_book_TDATA_blk_n <= time_from_book_TVALID_int_regslice;
        else 
            time_from_book_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    time_from_book_TREADY <= regslice_both_time_from_book_U_ack_in;

    time_from_book_TREADY_int_regslice_assign_proc : process(ap_CS_iter0_fsm_state3, ap_predicate_op37_read_state3, ap_block_state3_pp0_stage3_iter0, ap_block_state3_io, ap_block_state4_pp0_stage0_iter1, ap_block_state4_io, ap_CS_iter1_fsm_state4, ap_block_state5_pp0_stage1_iter1, ap_block_state5_io, ap_CS_iter1_fsm_state5, ap_done_reg)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state3_io) or (ap_const_boolean_1 = ap_block_state3_pp0_stage3_iter0) or (ap_done_reg = ap_const_logic_1) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state5) and ((ap_const_boolean_1 = ap_block_state5_io) or (ap_const_boolean_1 = ap_block_state5_pp0_stage1_iter1))) or ((ap_const_logic_1 = ap_CS_iter1_fsm_state4) and ((ap_const_boolean_1 = ap_block_state4_io) or (ap_const_boolean_1 = ap_block_state4_pp0_stage0_iter1))))) and (ap_predicate_op37_read_state3 = ap_const_boolean_1) and (ap_const_logic_1 = ap_CS_iter0_fsm_state3))) then 
            time_from_book_TREADY_int_regslice <= ap_const_logic_1;
        else 
            time_from_book_TREADY_int_regslice <= ap_const_logic_0;
        end if; 
    end process;

    tmp_3_nbreadreq_fu_84_p3 <= (0=>(time_from_book_TVALID_int_regslice), others=>'-');
    tmp_4_nbreadreq_fu_92_p3 <= (0=>(order_from_book_TVALID_int_regslice), others=>'-');
    tmp_nbreadreq_fu_76_p3 <= (0=>(metadata_from_book_TVALID_int_regslice), others=>'-');
    zext_ln215_fu_227_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln215_fu_221_p2),128));
end behav;
