-- ==============================================================
-- Generated by Vitis HLS v2023.2.1
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity Fast_processor is
port (
    lbRxDataIn_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    lbRxMetadataIn_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    lbRequestPortOpenOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    lbPortOpenReplyIn_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
    lbTxDataOut_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    lbTxMetadataOut_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    lbTxLengthOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
    tagsIn_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    tagsOut_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    metadata_to_book_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
    metadata_from_book_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
    time_to_book_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
    time_from_book_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
    order_to_book_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
    order_from_book_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    lbRxDataIn_TVALID : IN STD_LOGIC;
    lbRxDataIn_TREADY : OUT STD_LOGIC;
    lbRxMetadataIn_TVALID : IN STD_LOGIC;
    lbRxMetadataIn_TREADY : OUT STD_LOGIC;
    lbRequestPortOpenOut_TVALID : OUT STD_LOGIC;
    lbRequestPortOpenOut_TREADY : IN STD_LOGIC;
    lbPortOpenReplyIn_TVALID : IN STD_LOGIC;
    lbPortOpenReplyIn_TREADY : OUT STD_LOGIC;
    metadata_to_book_TVALID : OUT STD_LOGIC;
    metadata_to_book_TREADY : IN STD_LOGIC;
    tagsIn_TVALID : IN STD_LOGIC;
    tagsIn_TREADY : OUT STD_LOGIC;
    time_to_book_TVALID : OUT STD_LOGIC;
    time_to_book_TREADY : IN STD_LOGIC;
    order_to_book_TVALID : OUT STD_LOGIC;
    order_to_book_TREADY : IN STD_LOGIC;
    metadata_from_book_TVALID : IN STD_LOGIC;
    metadata_from_book_TREADY : OUT STD_LOGIC;
    lbTxDataOut_TVALID : OUT STD_LOGIC;
    lbTxDataOut_TREADY : IN STD_LOGIC;
    lbTxMetadataOut_TVALID : OUT STD_LOGIC;
    lbTxMetadataOut_TREADY : IN STD_LOGIC;
    lbTxLengthOut_TVALID : OUT STD_LOGIC;
    lbTxLengthOut_TREADY : IN STD_LOGIC;
    time_from_book_TVALID : IN STD_LOGIC;
    time_from_book_TREADY : OUT STD_LOGIC;
    tagsOut_TVALID : OUT STD_LOGIC;
    tagsOut_TREADY : IN STD_LOGIC;
    order_from_book_TVALID : IN STD_LOGIC;
    order_from_book_TREADY : OUT STD_LOGIC );
end;


architecture behav of Fast_processor is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "Fast_processor_Fast_processor,hls_ip_2023_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.149000,HLS_SYN_LAT=5,HLS_SYN_TPT=4,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=253,HLS_SYN_LUT=997,HLS_VERSION=2023_2_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';

    signal ap_rst_n_inv : STD_LOGIC;
    signal rxPath_U0_ap_start : STD_LOGIC;
    signal rxPath_U0_ap_done : STD_LOGIC;
    signal rxPath_U0_ap_continue : STD_LOGIC;
    signal rxPath_U0_ap_idle : STD_LOGIC;
    signal rxPath_U0_ap_ready : STD_LOGIC;
    signal rxPath_U0_lbRxDataIn_TREADY : STD_LOGIC;
    signal rxPath_U0_lbRxMetadataIn_TREADY : STD_LOGIC;
    signal rxPath_U0_lbRequestPortOpenOut_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal rxPath_U0_lbRequestPortOpenOut_TVALID : STD_LOGIC;
    signal rxPath_U0_lbPortOpenReplyIn_TREADY : STD_LOGIC;
    signal rxPath_U0_metadata_to_book_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal rxPath_U0_metadata_to_book_TVALID : STD_LOGIC;
    signal rxPath_U0_tagsIn_TREADY : STD_LOGIC;
    signal rxPath_U0_time_to_book_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal rxPath_U0_time_to_book_TVALID : STD_LOGIC;
    signal rxPath_U0_order_to_book_TDATA : STD_LOGIC_VECTOR (95 downto 0);
    signal rxPath_U0_order_to_book_TVALID : STD_LOGIC;
    signal txPath_U0_ap_start : STD_LOGIC;
    signal txPath_U0_ap_done : STD_LOGIC;
    signal txPath_U0_ap_continue : STD_LOGIC;
    signal txPath_U0_ap_idle : STD_LOGIC;
    signal txPath_U0_ap_ready : STD_LOGIC;
    signal txPath_U0_metadata_from_book_TREADY : STD_LOGIC;
    signal txPath_U0_lbTxDataOut_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal txPath_U0_lbTxDataOut_TVALID : STD_LOGIC;
    signal txPath_U0_lbTxMetadataOut_TDATA : STD_LOGIC_VECTOR (127 downto 0);
    signal txPath_U0_lbTxMetadataOut_TVALID : STD_LOGIC;
    signal txPath_U0_lbTxLengthOut_TDATA : STD_LOGIC_VECTOR (15 downto 0);
    signal txPath_U0_lbTxLengthOut_TVALID : STD_LOGIC;
    signal txPath_U0_time_from_book_TREADY : STD_LOGIC;
    signal txPath_U0_tagsOut_TDATA : STD_LOGIC_VECTOR (63 downto 0);
    signal txPath_U0_tagsOut_TVALID : STD_LOGIC;
    signal txPath_U0_order_from_book_TREADY : STD_LOGIC;

    component Fast_processor_rxPath IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        lbRxDataIn_TVALID : IN STD_LOGIC;
        tagsIn_TVALID : IN STD_LOGIC;
        time_to_book_TREADY : IN STD_LOGIC;
        lbRxMetadataIn_TVALID : IN STD_LOGIC;
        metadata_to_book_TREADY : IN STD_LOGIC;
        lbPortOpenReplyIn_TVALID : IN STD_LOGIC;
        order_to_book_TREADY : IN STD_LOGIC;
        lbRequestPortOpenOut_TREADY : IN STD_LOGIC;
        lbRxDataIn_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        lbRxDataIn_TREADY : OUT STD_LOGIC;
        lbRxMetadataIn_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        lbRxMetadataIn_TREADY : OUT STD_LOGIC;
        lbRequestPortOpenOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        lbRequestPortOpenOut_TVALID : OUT STD_LOGIC;
        lbPortOpenReplyIn_TDATA : IN STD_LOGIC_VECTOR (7 downto 0);
        lbPortOpenReplyIn_TREADY : OUT STD_LOGIC;
        metadata_to_book_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        metadata_to_book_TVALID : OUT STD_LOGIC;
        tagsIn_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        tagsIn_TREADY : OUT STD_LOGIC;
        time_to_book_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        time_to_book_TVALID : OUT STD_LOGIC;
        order_to_book_TDATA : OUT STD_LOGIC_VECTOR (95 downto 0);
        order_to_book_TVALID : OUT STD_LOGIC );
    end component;


    component Fast_processor_txPath IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_continue : IN STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        time_from_book_TVALID : IN STD_LOGIC;
        metadata_from_book_TVALID : IN STD_LOGIC;
        lbTxMetadataOut_TREADY : IN STD_LOGIC;
        order_from_book_TVALID : IN STD_LOGIC;
        lbTxDataOut_TREADY : IN STD_LOGIC;
        lbTxLengthOut_TREADY : IN STD_LOGIC;
        tagsOut_TREADY : IN STD_LOGIC;
        metadata_from_book_TDATA : IN STD_LOGIC_VECTOR (127 downto 0);
        metadata_from_book_TREADY : OUT STD_LOGIC;
        lbTxDataOut_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        lbTxDataOut_TVALID : OUT STD_LOGIC;
        lbTxMetadataOut_TDATA : OUT STD_LOGIC_VECTOR (127 downto 0);
        lbTxMetadataOut_TVALID : OUT STD_LOGIC;
        lbTxLengthOut_TDATA : OUT STD_LOGIC_VECTOR (15 downto 0);
        lbTxLengthOut_TVALID : OUT STD_LOGIC;
        time_from_book_TDATA : IN STD_LOGIC_VECTOR (63 downto 0);
        time_from_book_TREADY : OUT STD_LOGIC;
        tagsOut_TDATA : OUT STD_LOGIC_VECTOR (63 downto 0);
        tagsOut_TVALID : OUT STD_LOGIC;
        order_from_book_TDATA : IN STD_LOGIC_VECTOR (95 downto 0);
        order_from_book_TREADY : OUT STD_LOGIC );
    end component;



begin
    rxPath_U0 : component Fast_processor_rxPath
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => rxPath_U0_ap_start,
        ap_done => rxPath_U0_ap_done,
        ap_continue => rxPath_U0_ap_continue,
        ap_idle => rxPath_U0_ap_idle,
        ap_ready => rxPath_U0_ap_ready,
        lbRxDataIn_TVALID => lbRxDataIn_TVALID,
        tagsIn_TVALID => tagsIn_TVALID,
        time_to_book_TREADY => time_to_book_TREADY,
        lbRxMetadataIn_TVALID => lbRxMetadataIn_TVALID,
        metadata_to_book_TREADY => metadata_to_book_TREADY,
        lbPortOpenReplyIn_TVALID => lbPortOpenReplyIn_TVALID,
        order_to_book_TREADY => order_to_book_TREADY,
        lbRequestPortOpenOut_TREADY => lbRequestPortOpenOut_TREADY,
        lbRxDataIn_TDATA => lbRxDataIn_TDATA,
        lbRxDataIn_TREADY => rxPath_U0_lbRxDataIn_TREADY,
        lbRxMetadataIn_TDATA => lbRxMetadataIn_TDATA,
        lbRxMetadataIn_TREADY => rxPath_U0_lbRxMetadataIn_TREADY,
        lbRequestPortOpenOut_TDATA => rxPath_U0_lbRequestPortOpenOut_TDATA,
        lbRequestPortOpenOut_TVALID => rxPath_U0_lbRequestPortOpenOut_TVALID,
        lbPortOpenReplyIn_TDATA => lbPortOpenReplyIn_TDATA,
        lbPortOpenReplyIn_TREADY => rxPath_U0_lbPortOpenReplyIn_TREADY,
        metadata_to_book_TDATA => rxPath_U0_metadata_to_book_TDATA,
        metadata_to_book_TVALID => rxPath_U0_metadata_to_book_TVALID,
        tagsIn_TDATA => tagsIn_TDATA,
        tagsIn_TREADY => rxPath_U0_tagsIn_TREADY,
        time_to_book_TDATA => rxPath_U0_time_to_book_TDATA,
        time_to_book_TVALID => rxPath_U0_time_to_book_TVALID,
        order_to_book_TDATA => rxPath_U0_order_to_book_TDATA,
        order_to_book_TVALID => rxPath_U0_order_to_book_TVALID);

    txPath_U0 : component Fast_processor_txPath
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        ap_start => txPath_U0_ap_start,
        ap_done => txPath_U0_ap_done,
        ap_continue => txPath_U0_ap_continue,
        ap_idle => txPath_U0_ap_idle,
        ap_ready => txPath_U0_ap_ready,
        time_from_book_TVALID => time_from_book_TVALID,
        metadata_from_book_TVALID => metadata_from_book_TVALID,
        lbTxMetadataOut_TREADY => lbTxMetadataOut_TREADY,
        order_from_book_TVALID => order_from_book_TVALID,
        lbTxDataOut_TREADY => lbTxDataOut_TREADY,
        lbTxLengthOut_TREADY => lbTxLengthOut_TREADY,
        tagsOut_TREADY => tagsOut_TREADY,
        metadata_from_book_TDATA => metadata_from_book_TDATA,
        metadata_from_book_TREADY => txPath_U0_metadata_from_book_TREADY,
        lbTxDataOut_TDATA => txPath_U0_lbTxDataOut_TDATA,
        lbTxDataOut_TVALID => txPath_U0_lbTxDataOut_TVALID,
        lbTxMetadataOut_TDATA => txPath_U0_lbTxMetadataOut_TDATA,
        lbTxMetadataOut_TVALID => txPath_U0_lbTxMetadataOut_TVALID,
        lbTxLengthOut_TDATA => txPath_U0_lbTxLengthOut_TDATA,
        lbTxLengthOut_TVALID => txPath_U0_lbTxLengthOut_TVALID,
        time_from_book_TDATA => time_from_book_TDATA,
        time_from_book_TREADY => txPath_U0_time_from_book_TREADY,
        tagsOut_TDATA => txPath_U0_tagsOut_TDATA,
        tagsOut_TVALID => txPath_U0_tagsOut_TVALID,
        order_from_book_TDATA => order_from_book_TDATA,
        order_from_book_TREADY => txPath_U0_order_from_book_TREADY);





    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    lbPortOpenReplyIn_TREADY <= rxPath_U0_lbPortOpenReplyIn_TREADY;
    lbRequestPortOpenOut_TDATA <= rxPath_U0_lbRequestPortOpenOut_TDATA;
    lbRequestPortOpenOut_TVALID <= rxPath_U0_lbRequestPortOpenOut_TVALID;
    lbRxDataIn_TREADY <= rxPath_U0_lbRxDataIn_TREADY;
    lbRxMetadataIn_TREADY <= rxPath_U0_lbRxMetadataIn_TREADY;
    lbTxDataOut_TDATA <= txPath_U0_lbTxDataOut_TDATA;
    lbTxDataOut_TVALID <= txPath_U0_lbTxDataOut_TVALID;
    lbTxLengthOut_TDATA <= txPath_U0_lbTxLengthOut_TDATA;
    lbTxLengthOut_TVALID <= txPath_U0_lbTxLengthOut_TVALID;
    lbTxMetadataOut_TDATA <= txPath_U0_lbTxMetadataOut_TDATA;
    lbTxMetadataOut_TVALID <= txPath_U0_lbTxMetadataOut_TVALID;
    metadata_from_book_TREADY <= txPath_U0_metadata_from_book_TREADY;
    metadata_to_book_TDATA <= rxPath_U0_metadata_to_book_TDATA;
    metadata_to_book_TVALID <= rxPath_U0_metadata_to_book_TVALID;
    order_from_book_TREADY <= txPath_U0_order_from_book_TREADY;
    order_to_book_TDATA <= rxPath_U0_order_to_book_TDATA;
    order_to_book_TVALID <= rxPath_U0_order_to_book_TVALID;
    rxPath_U0_ap_continue <= ap_const_logic_1;
    rxPath_U0_ap_start <= ap_const_logic_1;
    tagsIn_TREADY <= rxPath_U0_tagsIn_TREADY;
    tagsOut_TDATA <= txPath_U0_tagsOut_TDATA;
    tagsOut_TVALID <= txPath_U0_tagsOut_TVALID;
    time_from_book_TREADY <= txPath_U0_time_from_book_TREADY;
    time_to_book_TDATA <= rxPath_U0_time_to_book_TDATA;
    time_to_book_TVALID <= rxPath_U0_time_to_book_TVALID;
    txPath_U0_ap_continue <= ap_const_logic_1;
    txPath_U0_ap_start <= ap_const_logic_1;
end behav;
