// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Fast_processor_rxPath (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        lbRxDataIn_TVALID,
        tagsIn_TVALID,
        time_to_book_TREADY,
        lbRxMetadataIn_TVALID,
        metadata_to_book_TREADY,
        lbPortOpenReplyIn_TVALID,
        order_to_book_TREADY,
        lbRequestPortOpenOut_TREADY,
        lbRxDataIn_TDATA,
        lbRxDataIn_TREADY,
        lbRxMetadataIn_TDATA,
        lbRxMetadataIn_TREADY,
        lbRequestPortOpenOut_TDATA,
        lbRequestPortOpenOut_TVALID,
        lbPortOpenReplyIn_TDATA,
        lbPortOpenReplyIn_TREADY,
        metadata_to_book_TDATA,
        metadata_to_book_TVALID,
        tagsIn_TDATA,
        tagsIn_TREADY,
        time_to_book_TDATA,
        time_to_book_TVALID,
        order_to_book_TDATA,
        order_to_book_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 2'd1;
parameter    ap_ST_iter0_fsm_state2 = 2'd2;
parameter    ap_ST_iter1_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   lbRxDataIn_TVALID;
input   tagsIn_TVALID;
input   time_to_book_TREADY;
input   lbRxMetadataIn_TVALID;
input   metadata_to_book_TREADY;
input   lbPortOpenReplyIn_TVALID;
input   order_to_book_TREADY;
input   lbRequestPortOpenOut_TREADY;
input  [127:0] lbRxDataIn_TDATA;
output   lbRxDataIn_TREADY;
input  [127:0] lbRxMetadataIn_TDATA;
output   lbRxMetadataIn_TREADY;
output  [15:0] lbRequestPortOpenOut_TDATA;
output   lbRequestPortOpenOut_TVALID;
input  [7:0] lbPortOpenReplyIn_TDATA;
output   lbPortOpenReplyIn_TREADY;
output  [127:0] metadata_to_book_TDATA;
output   metadata_to_book_TVALID;
input  [63:0] tagsIn_TDATA;
output   tagsIn_TREADY;
output  [63:0] time_to_book_TDATA;
output   time_to_book_TVALID;
output  [95:0] order_to_book_TDATA;
output   order_to_book_TVALID;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg   [1:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire    ap_CS_iter0_fsm_state2;
reg   [2:0] next_state_1_load_reg_1516;
reg   [0:0] tmp_s_reg_1520;
reg    ap_predicate_op27_read_state2;
reg   [0:0] tmp_9_reg_1524;
reg   [0:0] tmp_1_reg_1528;
reg    ap_predicate_op34_read_state2;
reg    ap_predicate_op35_write_state2;
reg    ap_predicate_op36_read_state2;
reg    ap_predicate_op42_write_state2;
reg    ap_predicate_op43_read_state2;
reg   [0:0] tmp_8_reg_1532;
reg    ap_predicate_op49_read_state2;
wire   [0:0] grp_nbwritereq_fu_256_p3;
reg    ap_predicate_op161_write_state2;
wire   [0:0] and_ln125_fu_1492_p2;
reg    ap_predicate_op172_write_state2;
reg    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state2_io;
reg   [2:0] next_state_1_load_reg_1516_pp0_iter0_reg;
reg   [0:0] tmp_9_reg_1524_pp0_iter0_reg;
reg   [0:0] tmp_1_reg_1528_pp0_iter0_reg;
reg    ap_predicate_op175_write_state3;
reg    ap_predicate_op176_write_state3;
reg   [0:0] tmp_19_reg_1546;
reg    ap_predicate_op180_write_state3;
reg   [0:0] and_ln125_reg_1555;
reg    ap_predicate_op182_write_state3;
wire    regslice_both_lbRequestPortOpenOut_U_apdone_blk;
wire    regslice_both_metadata_to_book_U_apdone_blk;
wire    regslice_both_time_to_book_U_apdone_blk;
wire    regslice_both_order_to_book_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter1;
reg    ap_block_state3_io;
wire    ap_CS_iter1_fsm_state3;
reg    ap_done_reg;
reg   [2:0] next_state_1;
reg   [63:0] first_packet;
reg   [42:0] second_packet;
reg   [31:0] openPortWaitTime;
reg    lbRxDataIn_TDATA_blk_n;
reg    lbRxMetadataIn_TDATA_blk_n;
reg    lbRequestPortOpenOut_TDATA_blk_n;
reg    lbPortOpenReplyIn_TDATA_blk_n;
reg    metadata_to_book_TDATA_blk_n;
reg    tagsIn_TDATA_blk_n;
reg    time_to_book_TDATA_blk_n;
reg    order_to_book_TDATA_blk_n;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] grp_nbreadreq_fu_232_p3;
wire   [0:0] tmp_1_nbreadreq_fu_240_p3;
wire   [0:0] tmp_8_nbreadreq_fu_248_p3;
wire   [2:0] select_ln147_fu_356_p3;
wire   [2:0] select_ln50_fu_431_p3;
wire   [63:0] trunc_ln41_fu_421_p1;
wire   [42:0] trunc_ln145_fu_346_p1;
wire   [31:0] add_ln129_fu_1498_p2;
wire   [0:0] grp_fu_326_p3;
wire   [31:0] tmp_28_fu_394_p4;
wire   [15:0] trunc_ln32_fu_370_p1;
wire   [31:0] tmp_27_fu_384_p4;
wire   [15:0] tmp_26_fu_374_p4;
wire   [0:0] tmp_2_fu_713_p3;
wire   [6:0] decoded_mantissa_fu_533_p4;
wire   [0:0] tmp_3_fu_731_p3;
wire   [6:0] trunc_ln42_9_fu_583_p4;
wire   [0:0] tmp_4_fu_747_p3;
wire   [6:0] trunc_ln42_3_fu_633_p4;
wire   [7:0] encoded_message_5_fu_573_p4;
wire   [7:0] encoded_message_7_fu_613_p4;
wire   [7:0] or_ln63_fu_763_p2;
wire   [7:0] encoded_message_3_fu_523_p4;
wire   [7:0] or_ln63_1_fu_769_p2;
wire   [0:0] tmp_5_fu_775_p3;
wire   [0:0] tmp_6_fu_789_p3;
wire   [0:0] xor_ln63_fu_721_p2;
wire   [0:0] and_ln63_fu_797_p2;
wire   [0:0] xor_ln63_1_fu_783_p2;
wire   [0:0] or_ln63_2_fu_803_p2;
wire   [2:0] select_ln63_1_fu_817_p3;
wire   [2:0] select_ln63_fu_809_p3;
wire   [7:0] zext_ln58_fu_727_p1;
wire   [7:0] or_ln_fu_755_p3;
wire   [7:0] decoded_mantissa_1_fu_739_p3;
wire   [7:0] select_ln63_3_fu_833_p3;
wire   [7:0] select_ln63_4_fu_841_p3;
wire   [7:0] tmp_7_fu_857_p2;
wire   [7:0] tmp_7_fu_857_p4;
wire   [7:0] tmp_7_fu_857_p6;
wire   [7:0] tmp_7_fu_857_p8;
wire   [7:0] tmp_7_fu_857_p9;
wire   [2:0] select_ln63_2_fu_825_p3;
wire   [7:0] tmp_7_fu_857_p11;
wire   [0:0] tmp_10_fu_885_p3;
wire   [0:0] trunc_ln86_fu_881_p1;
wire   [0:0] xor_ln86_fu_893_p2;
wire   [2:0] add_ln89_fu_899_p2;
wire   [2:0] message_offset_fu_911_p3;
wire   [6:0] tmp_11_fu_923_p2;
wire   [6:0] tmp_11_fu_923_p4;
wire   [6:0] tmp_11_fu_923_p6;
wire   [6:0] tmp_11_fu_923_p8;
wire   [6:0] tmp_11_fu_923_p10;
wire   [6:0] tmp_11_fu_923_p11;
wire   [7:0] orderID_buff_fu_951_p2;
wire   [7:0] orderID_buff_fu_951_p4;
wire   [7:0] orderID_buff_fu_951_p6;
wire   [7:0] orderID_buff_fu_951_p8;
wire   [7:0] encoded_message_fu_451_p1;
wire   [7:0] orderID_buff_fu_951_p11;
wire   [7:0] orderID_buff_fu_951_p13;
wire   [7:0] tmp_13_fu_991_p2;
wire   [7:0] tmp_13_fu_991_p4;
wire   [7:0] tmp_13_fu_991_p6;
wire   [7:0] tmp_13_fu_991_p10;
wire   [7:0] tmp_13_fu_991_p11;
wire   [7:0] tmp_13_fu_991_p13;
wire   [7:0] shl_ln106_fu_1027_p2;
wire   [6:0] tmp_14_fu_1039_p4;
wire   [7:0] or_ln106_fu_1033_p2;
wire   [14:0] orderID_buff_1_fu_1059_p3;
wire   [7:0] tmp_15_fu_1071_p2;
wire   [7:0] tmp_15_fu_1071_p4;
wire   [7:0] tmp_15_fu_1071_p8;
wire   [7:0] tmp_15_fu_1071_p10;
wire   [7:0] tmp_15_fu_1071_p11;
wire   [7:0] tmp_15_fu_1071_p13;
wire   [7:0] shl_ln106_1_fu_1107_p2;
wire   [6:0] tmp_20_fu_1119_p4;
wire   [7:0] or_ln106_1_fu_1113_p2;
wire   [21:0] orderID_buff_2_fu_1129_p4;
wire   [7:0] tmp_16_fu_1143_p2;
wire   [7:0] tmp_16_fu_1143_p6;
wire   [7:0] tmp_16_fu_1143_p8;
wire   [7:0] tmp_16_fu_1143_p10;
wire   [7:0] tmp_16_fu_1143_p11;
wire   [7:0] tmp_16_fu_1143_p13;
wire   [7:0] shl_ln106_2_fu_1179_p2;
wire   [2:0] trunc_ln_fu_1049_p4;
wire   [6:0] tmp_21_fu_1191_p4;
wire   [7:0] or_ln106_2_fu_1185_p2;
wire   [0:0] tmp_12_fu_979_p3;
wire   [24:0] orderID_buff_3_fu_1201_p5;
wire   [0:0] tmp_18_fu_1019_p3;
wire   [0:0] xor_ln101_fu_1221_p2;
wire   [0:0] and_ln101_fu_1227_p2;
wire   [24:0] zext_ln48_fu_987_p1;
wire   [24:0] select_ln101_fu_1213_p3;
wire   [7:0] or_ln101_fu_1241_p2;
wire   [0:0] tmp_24_fu_1247_p3;
wire   [0:0] tmp_22_fu_1099_p3;
wire   [0:0] xor_ln101_2_fu_1255_p2;
wire   [0:0] and_ln101_1_fu_1261_p2;
wire   [24:0] zext_ln48_1_fu_1067_p1;
wire   [24:0] select_ln101_1_fu_1233_p3;
wire   [0:0] tmp_23_fu_1171_p3;
wire   [0:0] xor_ln101_1_fu_1275_p2;
wire   [0:0] and_ln101_2_fu_1281_p2;
wire   [0:0] and_ln101_3_fu_1287_p2;
wire   [24:0] zext_ln48_2_fu_1139_p1;
wire   [24:0] select_ln101_2_fu_1267_p3;
wire   [0:0] or_ln101_1_fu_1309_p2;
wire   [2:0] select_ln101_4_fu_1301_p3;
wire   [2:0] select_ln101_5_fu_1315_p3;
wire   [0:0] or_ln101_2_fu_1323_p2;
wire   [0:0] or_ln101_3_fu_1337_p2;
wire   [2:0] select_ln101_6_fu_1329_p3;
wire   [2:0] select_ln101_7_fu_1343_p3;
wire   [3:0] zext_ln101_fu_1351_p1;
wire   [3:0] zext_ln47_fu_919_p1;
wire   [6:0] tmp_17_fu_1361_p2;
wire   [6:0] tmp_17_fu_1361_p4;
wire   [6:0] tmp_17_fu_1361_p6;
wire   [6:0] tmp_17_fu_1361_p8;
wire   [6:0] tmp_17_fu_1361_p10;
wire   [6:0] tmp_17_fu_1361_p12;
wire   [6:0] tmp_17_fu_1361_p14;
wire   [6:0] tmp_17_fu_1361_p16;
wire   [6:0] tmp_17_fu_1361_p18;
wire   [6:0] tmp_17_fu_1361_p19;
wire   [3:0] message_offset_1_fu_1355_p2;
wire   [2:0] order_type_buff_fu_1405_p2;
wire   [2:0] order_type_buff_fu_1405_p4;
wire   [2:0] order_type_buff_fu_1405_p6;
wire   [2:0] order_type_buff_fu_1405_p8;
wire   [2:0] order_type_buff_fu_1405_p10;
wire   [2:0] order_type_buff_fu_1405_p12;
wire   [2:0] order_type_buff_fu_1405_p14;
wire   [2:0] order_type_buff_fu_1405_p16;
wire   [2:0] order_type_buff_fu_1405_p18;
wire   [2:0] order_type_buff_fu_1405_p19;
wire   [2:0] order_type_buff_fu_1405_p21;
wire   [24:0] select_ln101_3_fu_1293_p3;
wire   [6:0] tmp_17_fu_1361_p21;
wire   [0:0] size_buff_fu_905_p2;
wire   [6:0] tmp_11_fu_923_p13;
wire   [7:0] select_ln63_5_fu_849_p3;
wire   [67:0] or_ln76_2_fu_1449_p10;
wire   [0:0] and_ln125_fu_1492_p0;
wire   [0:0] icmp_ln125_fu_1486_p2;
reg   [1:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter0_fsm_state2_blk;
reg    ap_ST_iter1_fsm_state3_blk;
wire    regslice_both_lbRxDataIn_U_apdone_blk;
wire   [127:0] lbRxDataIn_TDATA_int_regslice;
wire    lbRxDataIn_TVALID_int_regslice;
reg    lbRxDataIn_TREADY_int_regslice;
wire    regslice_both_lbRxDataIn_U_ack_in;
wire    regslice_both_lbRxMetadataIn_U_apdone_blk;
wire   [127:0] lbRxMetadataIn_TDATA_int_regslice;
wire    lbRxMetadataIn_TVALID_int_regslice;
reg    lbRxMetadataIn_TREADY_int_regslice;
wire    regslice_both_lbRxMetadataIn_U_ack_in;
reg    lbRequestPortOpenOut_TVALID_int_regslice;
wire    lbRequestPortOpenOut_TREADY_int_regslice;
wire    regslice_both_lbRequestPortOpenOut_U_vld_out;
wire    regslice_both_lbPortOpenReplyIn_U_apdone_blk;
wire   [7:0] lbPortOpenReplyIn_TDATA_int_regslice;
wire    lbPortOpenReplyIn_TVALID_int_regslice;
reg    lbPortOpenReplyIn_TREADY_int_regslice;
wire    regslice_both_lbPortOpenReplyIn_U_ack_in;
wire   [127:0] metadata_to_book_TDATA_int_regslice;
reg    metadata_to_book_TVALID_int_regslice;
wire    metadata_to_book_TREADY_int_regslice;
wire    regslice_both_metadata_to_book_U_vld_out;
wire    regslice_both_tagsIn_U_apdone_blk;
wire   [63:0] tagsIn_TDATA_int_regslice;
wire    tagsIn_TVALID_int_regslice;
reg    tagsIn_TREADY_int_regslice;
wire    regslice_both_tagsIn_U_ack_in;
reg    time_to_book_TVALID_int_regslice;
wire    time_to_book_TREADY_int_regslice;
wire    regslice_both_time_to_book_U_vld_out;
wire   [95:0] order_to_book_TDATA_int_regslice;
reg    order_to_book_TVALID_int_regslice;
wire    order_to_book_TREADY_int_regslice;
wire    regslice_both_order_to_book_U_vld_out;
wire   [2:0] tmp_7_fu_857_p1;
wire  signed [2:0] tmp_7_fu_857_p3;
wire  signed [2:0] tmp_7_fu_857_p5;
wire  signed [2:0] tmp_7_fu_857_p7;
wire   [2:0] tmp_11_fu_923_p1;
wire  signed [2:0] tmp_11_fu_923_p3;
wire  signed [2:0] tmp_11_fu_923_p5;
wire  signed [2:0] tmp_11_fu_923_p7;
wire  signed [2:0] tmp_11_fu_923_p9;
wire   [2:0] orderID_buff_fu_951_p1;
wire  signed [2:0] orderID_buff_fu_951_p3;
wire  signed [2:0] orderID_buff_fu_951_p5;
wire  signed [2:0] orderID_buff_fu_951_p7;
wire  signed [2:0] orderID_buff_fu_951_p9;
wire   [2:0] tmp_13_fu_991_p1;
wire  signed [2:0] tmp_13_fu_991_p3;
wire  signed [2:0] tmp_13_fu_991_p5;
wire  signed [2:0] tmp_13_fu_991_p7;
wire  signed [2:0] tmp_13_fu_991_p9;
wire   [2:0] tmp_15_fu_1071_p1;
wire  signed [2:0] tmp_15_fu_1071_p3;
wire  signed [2:0] tmp_15_fu_1071_p5;
wire  signed [2:0] tmp_15_fu_1071_p7;
wire  signed [2:0] tmp_15_fu_1071_p9;
wire   [2:0] tmp_16_fu_1143_p1;
wire  signed [2:0] tmp_16_fu_1143_p3;
wire  signed [2:0] tmp_16_fu_1143_p5;
wire  signed [2:0] tmp_16_fu_1143_p7;
wire  signed [2:0] tmp_16_fu_1143_p9;
wire   [3:0] tmp_17_fu_1361_p1;
wire   [3:0] tmp_17_fu_1361_p3;
wire   [3:0] tmp_17_fu_1361_p5;
wire   [3:0] tmp_17_fu_1361_p7;
wire  signed [3:0] tmp_17_fu_1361_p9;
wire  signed [3:0] tmp_17_fu_1361_p11;
wire  signed [3:0] tmp_17_fu_1361_p13;
wire  signed [3:0] tmp_17_fu_1361_p15;
wire  signed [3:0] tmp_17_fu_1361_p17;
wire   [3:0] order_type_buff_fu_1405_p1;
wire   [3:0] order_type_buff_fu_1405_p3;
wire   [3:0] order_type_buff_fu_1405_p5;
wire   [3:0] order_type_buff_fu_1405_p7;
wire  signed [3:0] order_type_buff_fu_1405_p9;
wire  signed [3:0] order_type_buff_fu_1405_p11;
wire  signed [3:0] order_type_buff_fu_1405_p13;
wire  signed [3:0] order_type_buff_fu_1405_p15;
wire  signed [3:0] order_type_buff_fu_1405_p17;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 2'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_done_reg = 1'b0;
#0 next_state_1 = 3'd0;
#0 first_packet = 64'd0;
#0 second_packet = 43'd0;
#0 openPortWaitTime = 32'd100;
end

Fast_processor_sparsemux_9_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h5 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h6 ),
    .din3_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_9_3_8_1_1_U1(
    .din0(tmp_7_fu_857_p2),
    .din1(tmp_7_fu_857_p4),
    .din2(tmp_7_fu_857_p6),
    .din3(tmp_7_fu_857_p8),
    .def(tmp_7_fu_857_p9),
    .sel(select_ln63_2_fu_825_p3),
    .dout(tmp_7_fu_857_p11)
);

Fast_processor_sparsemux_11_3_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 7 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 7 ),
    .CASE2( 3'h5 ),
    .din2_WIDTH( 7 ),
    .CASE3( 3'h6 ),
    .din3_WIDTH( 7 ),
    .CASE4( 3'h7 ),
    .din4_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 7 ))
sparsemux_11_3_7_1_1_U2(
    .din0(tmp_11_fu_923_p2),
    .din1(tmp_11_fu_923_p4),
    .din2(tmp_11_fu_923_p6),
    .din3(tmp_11_fu_923_p8),
    .din4(tmp_11_fu_923_p10),
    .def(tmp_11_fu_923_p11),
    .sel(message_offset_fu_911_p3),
    .dout(tmp_11_fu_923_p13)
);

Fast_processor_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h5 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h6 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h7 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U3(
    .din0(orderID_buff_fu_951_p2),
    .din1(orderID_buff_fu_951_p4),
    .din2(orderID_buff_fu_951_p6),
    .din3(orderID_buff_fu_951_p8),
    .din4(encoded_message_fu_451_p1),
    .def(orderID_buff_fu_951_p11),
    .sel(message_offset_fu_911_p3),
    .dout(orderID_buff_fu_951_p13)
);

Fast_processor_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h5 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h6 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h7 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U4(
    .din0(tmp_13_fu_991_p2),
    .din1(tmp_13_fu_991_p4),
    .din2(tmp_13_fu_991_p6),
    .din3(encoded_message_fu_451_p1),
    .din4(tmp_13_fu_991_p10),
    .def(tmp_13_fu_991_p11),
    .sel(message_offset_fu_911_p3),
    .dout(tmp_13_fu_991_p13)
);

Fast_processor_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h5 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h6 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h7 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U5(
    .din0(tmp_15_fu_1071_p2),
    .din1(tmp_15_fu_1071_p4),
    .din2(encoded_message_fu_451_p1),
    .din3(tmp_15_fu_1071_p8),
    .din4(tmp_15_fu_1071_p10),
    .def(tmp_15_fu_1071_p11),
    .sel(message_offset_fu_911_p3),
    .dout(tmp_15_fu_1071_p13)
);

Fast_processor_sparsemux_11_3_8_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 3'h3 ),
    .din0_WIDTH( 8 ),
    .CASE1( 3'h4 ),
    .din1_WIDTH( 8 ),
    .CASE2( 3'h5 ),
    .din2_WIDTH( 8 ),
    .CASE3( 3'h6 ),
    .din3_WIDTH( 8 ),
    .CASE4( 3'h7 ),
    .din4_WIDTH( 8 ),
    .def_WIDTH( 8 ),
    .sel_WIDTH( 3 ),
    .dout_WIDTH( 8 ))
sparsemux_11_3_8_1_1_U6(
    .din0(tmp_16_fu_1143_p2),
    .din1(encoded_message_fu_451_p1),
    .din2(tmp_16_fu_1143_p6),
    .din3(tmp_16_fu_1143_p8),
    .din4(tmp_16_fu_1143_p10),
    .def(tmp_16_fu_1143_p11),
    .sel(message_offset_fu_911_p3),
    .dout(tmp_16_fu_1143_p13)
);

Fast_processor_sparsemux_19_4_7_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h4 ),
    .din0_WIDTH( 7 ),
    .CASE1( 4'h5 ),
    .din1_WIDTH( 7 ),
    .CASE2( 4'h6 ),
    .din2_WIDTH( 7 ),
    .CASE3( 4'h7 ),
    .din3_WIDTH( 7 ),
    .CASE4( 4'h8 ),
    .din4_WIDTH( 7 ),
    .CASE5( 4'h9 ),
    .din5_WIDTH( 7 ),
    .CASE6( 4'hA ),
    .din6_WIDTH( 7 ),
    .CASE7( 4'hB ),
    .din7_WIDTH( 7 ),
    .CASE8( 4'hC ),
    .din8_WIDTH( 7 ),
    .def_WIDTH( 7 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 7 ))
sparsemux_19_4_7_1_1_U7(
    .din0(tmp_17_fu_1361_p2),
    .din1(tmp_17_fu_1361_p4),
    .din2(tmp_17_fu_1361_p6),
    .din3(tmp_17_fu_1361_p8),
    .din4(tmp_17_fu_1361_p10),
    .din5(tmp_17_fu_1361_p12),
    .din6(tmp_17_fu_1361_p14),
    .din7(tmp_17_fu_1361_p16),
    .din8(tmp_17_fu_1361_p18),
    .def(tmp_17_fu_1361_p19),
    .sel(message_offset_1_fu_1355_p2),
    .dout(tmp_17_fu_1361_p21)
);

Fast_processor_sparsemux_19_4_3_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h4 ),
    .din0_WIDTH( 3 ),
    .CASE1( 4'h5 ),
    .din1_WIDTH( 3 ),
    .CASE2( 4'h6 ),
    .din2_WIDTH( 3 ),
    .CASE3( 4'h7 ),
    .din3_WIDTH( 3 ),
    .CASE4( 4'h8 ),
    .din4_WIDTH( 3 ),
    .CASE5( 4'h9 ),
    .din5_WIDTH( 3 ),
    .CASE6( 4'hA ),
    .din6_WIDTH( 3 ),
    .CASE7( 4'hB ),
    .din7_WIDTH( 3 ),
    .CASE8( 4'hC ),
    .din8_WIDTH( 3 ),
    .def_WIDTH( 3 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 3 ))
sparsemux_19_4_3_1_1_U8(
    .din0(order_type_buff_fu_1405_p2),
    .din1(order_type_buff_fu_1405_p4),
    .din2(order_type_buff_fu_1405_p6),
    .din3(order_type_buff_fu_1405_p8),
    .din4(order_type_buff_fu_1405_p10),
    .din5(order_type_buff_fu_1405_p12),
    .din6(order_type_buff_fu_1405_p14),
    .din7(order_type_buff_fu_1405_p16),
    .din8(order_type_buff_fu_1405_p18),
    .def(order_type_buff_fu_1405_p19),
    .sel(message_offset_1_fu_1355_p2),
    .dout(order_type_buff_fu_1405_p21)
);

Fast_processor_regslice_both #(
    .DataWidth( 128 ))
regslice_both_lbRxDataIn_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(lbRxDataIn_TDATA),
    .vld_in(lbRxDataIn_TVALID),
    .ack_in(regslice_both_lbRxDataIn_U_ack_in),
    .data_out(lbRxDataIn_TDATA_int_regslice),
    .vld_out(lbRxDataIn_TVALID_int_regslice),
    .ack_out(lbRxDataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_lbRxDataIn_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 128 ))
regslice_both_lbRxMetadataIn_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(lbRxMetadataIn_TDATA),
    .vld_in(lbRxMetadataIn_TVALID),
    .ack_in(regslice_both_lbRxMetadataIn_U_ack_in),
    .data_out(lbRxMetadataIn_TDATA_int_regslice),
    .vld_out(lbRxMetadataIn_TVALID_int_regslice),
    .ack_out(lbRxMetadataIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_lbRxMetadataIn_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 16 ))
regslice_both_lbRequestPortOpenOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(16'd49152),
    .vld_in(lbRequestPortOpenOut_TVALID_int_regslice),
    .ack_in(lbRequestPortOpenOut_TREADY_int_regslice),
    .data_out(lbRequestPortOpenOut_TDATA),
    .vld_out(regslice_both_lbRequestPortOpenOut_U_vld_out),
    .ack_out(lbRequestPortOpenOut_TREADY),
    .apdone_blk(regslice_both_lbRequestPortOpenOut_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 8 ))
regslice_both_lbPortOpenReplyIn_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(lbPortOpenReplyIn_TDATA),
    .vld_in(lbPortOpenReplyIn_TVALID),
    .ack_in(regslice_both_lbPortOpenReplyIn_U_ack_in),
    .data_out(lbPortOpenReplyIn_TDATA_int_regslice),
    .vld_out(lbPortOpenReplyIn_TVALID_int_regslice),
    .ack_out(lbPortOpenReplyIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_lbPortOpenReplyIn_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 128 ))
regslice_both_metadata_to_book_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(metadata_to_book_TDATA_int_regslice),
    .vld_in(metadata_to_book_TVALID_int_regslice),
    .ack_in(metadata_to_book_TREADY_int_regslice),
    .data_out(metadata_to_book_TDATA),
    .vld_out(regslice_both_metadata_to_book_U_vld_out),
    .ack_out(metadata_to_book_TREADY),
    .apdone_blk(regslice_both_metadata_to_book_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 64 ))
regslice_both_tagsIn_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tagsIn_TDATA),
    .vld_in(tagsIn_TVALID),
    .ack_in(regslice_both_tagsIn_U_ack_in),
    .data_out(tagsIn_TDATA_int_regslice),
    .vld_out(tagsIn_TVALID_int_regslice),
    .ack_out(tagsIn_TREADY_int_regslice),
    .apdone_blk(regslice_both_tagsIn_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 64 ))
regslice_both_time_to_book_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(tagsIn_TDATA_int_regslice),
    .vld_in(time_to_book_TVALID_int_regslice),
    .ack_in(time_to_book_TREADY_int_regslice),
    .data_out(time_to_book_TDATA),
    .vld_out(regslice_both_time_to_book_U_vld_out),
    .ack_out(time_to_book_TREADY),
    .apdone_blk(regslice_both_time_to_book_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 96 ))
regslice_both_order_to_book_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(order_to_book_TDATA_int_regslice),
    .vld_in(order_to_book_TVALID_int_regslice),
    .ack_in(order_to_book_TREADY_int_regslice),
    .data_out(order_to_book_TDATA),
    .vld_out(regslice_both_order_to_book_U_vld_out),
    .ack_out(order_to_book_TREADY),
    .apdone_blk(regslice_both_order_to_book_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(next_state_1_load_reg_1516 == 3'd4) & ~(next_state_1_load_reg_1516 == 3'd1) & ~(next_state_1_load_reg_1516 == 3'd2) & ~(next_state_1_load_reg_1516 == 3'd3) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'd1 == and_ln125_fu_1492_p2) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        next_state_1 <= 3'd1;
    end else if (((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (next_state_1_load_reg_1516 == 3'd4) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (tmp_8_reg_1532 == 1'd1) & (next_state_1_load_reg_1516 == 3'd1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        next_state_1 <= 3'd2;
    end else if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        next_state_1 <= select_ln50_fu_431_p3;
    end else if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (tmp_s_reg_1520 == 1'd1) & (next_state_1_load_reg_1516 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        next_state_1 <= select_ln147_fu_356_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        and_ln125_reg_1555 <= and_ln125_fu_1492_p2;
        next_state_1_load_reg_1516_pp0_iter0_reg <= next_state_1_load_reg_1516;
        tmp_19_reg_1546 <= order_to_book_TREADY_int_regslice;
        tmp_1_reg_1528_pp0_iter0_reg <= tmp_1_reg_1528;
        tmp_9_reg_1524_pp0_iter0_reg <= tmp_9_reg_1524;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        first_packet <= trunc_ln41_fu_421_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        next_state_1_load_reg_1516 <= next_state_1;
        tmp_1_reg_1528 <= tmp_1_nbreadreq_fu_240_p3;
        tmp_8_reg_1532 <= tmp_8_nbreadreq_fu_248_p3;
        tmp_9_reg_1524 <= grp_nbreadreq_fu_232_p3;
        tmp_s_reg_1520 <= grp_nbreadreq_fu_232_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~(next_state_1_load_reg_1516 == 3'd4) & ~(next_state_1_load_reg_1516 == 3'd1) & ~(next_state_1_load_reg_1516 == 3'd2) & ~(next_state_1_load_reg_1516 == 3'd3) & ~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2) & (1'd0 == and_ln125_fu_1492_p2))) begin
        openPortWaitTime <= add_ln129_fu_1498_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (tmp_s_reg_1520 == 1'd1) & (next_state_1_load_reg_1516 == 3'd3) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        second_packet <= trunc_ln145_fu_346_p1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0))) begin
        ap_ST_iter0_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state3))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op49_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        lbPortOpenReplyIn_TDATA_blk_n = lbPortOpenReplyIn_TVALID_int_regslice;
    end else begin
        lbPortOpenReplyIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op49_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        lbPortOpenReplyIn_TREADY_int_regslice = 1'b1;
    end else begin
        lbPortOpenReplyIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter0_fsm_state2) & (ap_predicate_op172_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op182_write_state3 == 1'b1)))) begin
        lbRequestPortOpenOut_TDATA_blk_n = lbRequestPortOpenOut_TREADY_int_regslice;
    end else begin
        lbRequestPortOpenOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2) & (ap_predicate_op172_write_state2 == 1'b1))) begin
        lbRequestPortOpenOut_TVALID_int_regslice = 1'b1;
    end else begin
        lbRequestPortOpenOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op43_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((ap_predicate_op27_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        lbRxDataIn_TDATA_blk_n = lbRxDataIn_TVALID_int_regslice;
    end else begin
        lbRxDataIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op43_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | (~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op27_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)))) begin
        lbRxDataIn_TREADY_int_regslice = 1'b1;
    end else begin
        lbRxDataIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op36_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        lbRxMetadataIn_TDATA_blk_n = lbRxMetadataIn_TVALID_int_regslice;
    end else begin
        lbRxMetadataIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op36_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        lbRxMetadataIn_TREADY_int_regslice = 1'b1;
    end else begin
        lbRxMetadataIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op42_write_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op176_write_state3 == 1'b1)))) begin
        metadata_to_book_TDATA_blk_n = metadata_to_book_TREADY_int_regslice;
    end else begin
        metadata_to_book_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op42_write_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        metadata_to_book_TVALID_int_regslice = 1'b1;
    end else begin
        metadata_to_book_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter0_fsm_state2) & (ap_predicate_op161_write_state2 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op180_write_state3 == 1'b1)))) begin
        order_to_book_TDATA_blk_n = order_to_book_TREADY_int_regslice;
    end else begin
        order_to_book_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2) & (ap_predicate_op161_write_state2 == 1'b1))) begin
        order_to_book_TVALID_int_regslice = 1'b1;
    end else begin
        order_to_book_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op34_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        tagsIn_TDATA_blk_n = tagsIn_TVALID_int_regslice;
    end else begin
        tagsIn_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op34_read_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        tagsIn_TREADY_int_regslice = 1'b1;
    end else begin
        tagsIn_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op35_write_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2)) | ((1'b1 == ap_CS_iter1_fsm_state3) & (ap_predicate_op175_write_state3 == 1'b1)))) begin
        time_to_book_TDATA_blk_n = time_to_book_TREADY_int_regslice;
    end else begin
        time_to_book_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (ap_predicate_op35_write_state2 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        time_to_book_TVALID_int_regslice = 1'b1;
    end else begin
        time_to_book_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if (~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0)) & ~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & ((1'b0 == ap_CS_iter0_fsm_state2) | ((1'b1 == ap_CS_iter0_fsm_state2) & ((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0)))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | (1'b1 == ap_block_state2_pp0_stage1_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state3;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign add_ln129_fu_1498_p2 = ($signed(openPortWaitTime) + $signed(32'd4294967295));

assign add_ln89_fu_899_p2 = (select_ln63_2_fu_825_p3 + 3'd1);

assign and_ln101_1_fu_1261_p2 = (xor_ln101_2_fu_1255_p2 & tmp_22_fu_1099_p3);

assign and_ln101_2_fu_1281_p2 = (xor_ln101_1_fu_1275_p2 & tmp_23_fu_1171_p3);

assign and_ln101_3_fu_1287_p2 = (xor_ln101_2_fu_1255_p2 & and_ln101_2_fu_1281_p2);

assign and_ln101_fu_1227_p2 = (xor_ln101_fu_1221_p2 & tmp_18_fu_1019_p3);

assign and_ln125_fu_1492_p0 = lbRequestPortOpenOut_TREADY_int_regslice;

assign and_ln125_fu_1492_p2 = (icmp_ln125_fu_1486_p2 & and_ln125_fu_1492_p0);

assign and_ln63_fu_797_p2 = (xor_ln63_fu_721_p2 & tmp_6_fu_789_p3);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state3 = ap_CS_iter1_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = (((ap_predicate_op42_write_state2 == 1'b1) & (metadata_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op35_write_state2 == 1'b1) & (time_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op172_write_state2 == 1'b1) & (lbRequestPortOpenOut_TREADY_int_regslice == 1'b0)) | ((order_to_book_TREADY_int_regslice == 1'b0) & (ap_predicate_op161_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state2_pp0_stage1_iter0 = (((ap_predicate_op49_read_state2 == 1'b1) & (lbPortOpenReplyIn_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op43_read_state2 == 1'b1) & (lbRxDataIn_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op42_write_state2 == 1'b1) & (metadata_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op36_read_state2 == 1'b1) & (lbRxMetadataIn_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op35_write_state2 == 1'b1) & (time_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op34_read_state2 == 1'b1) & (tagsIn_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op27_read_state2 == 1'b1) & (lbRxDataIn_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op172_write_state2 == 1'b1) & (lbRequestPortOpenOut_TREADY_int_regslice == 1'b0)) | ((order_to_book_TREADY_int_regslice == 1'b0) & (ap_predicate_op161_write_state2 == 1'b1)));
end

always @ (*) begin
    ap_block_state3_io = (((ap_predicate_op182_write_state3 == 1'b1) & (lbRequestPortOpenOut_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op180_write_state3 == 1'b1) & (order_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op176_write_state3 == 1'b1) & (metadata_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op175_write_state3 == 1'b1) & (time_to_book_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter1 = ((regslice_both_order_to_book_U_apdone_blk == 1'b1) | (regslice_both_time_to_book_U_apdone_blk == 1'b1) | (regslice_both_metadata_to_book_U_apdone_blk == 1'b1) | (regslice_both_lbRequestPortOpenOut_U_apdone_blk == 1'b1) | ((ap_predicate_op182_write_state3 == 1'b1) & (lbRequestPortOpenOut_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op180_write_state3 == 1'b1) & (order_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op176_write_state3 == 1'b1) & (metadata_to_book_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op175_write_state3 == 1'b1) & (time_to_book_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_predicate_op161_write_state2 = ((next_state_1_load_reg_1516 == 3'd4) & (grp_nbwritereq_fu_256_p3 == 1'd1));
end

always @ (*) begin
    ap_predicate_op172_write_state2 = (~(next_state_1_load_reg_1516 == 3'd4) & ~(next_state_1_load_reg_1516 == 3'd1) & ~(next_state_1_load_reg_1516 == 3'd2) & ~(next_state_1_load_reg_1516 == 3'd3) & (1'd1 == and_ln125_fu_1492_p2));
end

always @ (*) begin
    ap_predicate_op175_write_state3 = ((tmp_1_reg_1528_pp0_iter0_reg == 1'd1) & (tmp_9_reg_1524_pp0_iter0_reg == 1'd1) & (next_state_1_load_reg_1516_pp0_iter0_reg == 3'd2));
end

always @ (*) begin
    ap_predicate_op176_write_state3 = ((tmp_1_reg_1528_pp0_iter0_reg == 1'd1) & (tmp_9_reg_1524_pp0_iter0_reg == 1'd1) & (next_state_1_load_reg_1516_pp0_iter0_reg == 3'd2));
end

always @ (*) begin
    ap_predicate_op180_write_state3 = ((tmp_19_reg_1546 == 1'd1) & (next_state_1_load_reg_1516_pp0_iter0_reg == 3'd4));
end

always @ (*) begin
    ap_predicate_op182_write_state3 = (~(next_state_1_load_reg_1516_pp0_iter0_reg == 3'd3) & ~(next_state_1_load_reg_1516_pp0_iter0_reg == 3'd1) & ~(next_state_1_load_reg_1516_pp0_iter0_reg == 3'd4) & ~(next_state_1_load_reg_1516_pp0_iter0_reg == 3'd2) & (1'd1 == and_ln125_reg_1555));
end

always @ (*) begin
    ap_predicate_op27_read_state2 = ((tmp_s_reg_1520 == 1'd1) & (next_state_1_load_reg_1516 == 3'd3));
end

always @ (*) begin
    ap_predicate_op34_read_state2 = ((tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2));
end

always @ (*) begin
    ap_predicate_op35_write_state2 = ((tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2));
end

always @ (*) begin
    ap_predicate_op36_read_state2 = ((tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2));
end

always @ (*) begin
    ap_predicate_op42_write_state2 = ((tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2));
end

always @ (*) begin
    ap_predicate_op43_read_state2 = ((tmp_1_reg_1528 == 1'd1) & (tmp_9_reg_1524 == 1'd1) & (next_state_1_load_reg_1516 == 3'd2));
end

always @ (*) begin
    ap_predicate_op49_read_state2 = ((tmp_8_reg_1532 == 1'd1) & (next_state_1_load_reg_1516 == 3'd1));
end

assign decoded_mantissa_1_fu_739_p3 = {{tmp_3_fu_731_p3}, {trunc_ln42_9_fu_583_p4}};

assign decoded_mantissa_fu_533_p4 = {{first_packet[30:24]}};

assign encoded_message_3_fu_523_p4 = {{first_packet[31:24]}};

assign encoded_message_5_fu_573_p4 = {{first_packet[39:32]}};

assign encoded_message_7_fu_613_p4 = {{first_packet[47:40]}};

assign encoded_message_fu_451_p1 = second_packet[7:0];

assign grp_fu_326_p3 = lbRxDataIn_TDATA_int_regslice[128'd72];

assign grp_nbreadreq_fu_232_p3 = lbRxDataIn_TVALID_int_regslice;

assign grp_nbwritereq_fu_256_p3 = order_to_book_TREADY_int_regslice;

assign icmp_ln125_fu_1486_p2 = ((openPortWaitTime == 32'd0) ? 1'b1 : 1'b0);

assign lbPortOpenReplyIn_TREADY = regslice_both_lbPortOpenReplyIn_U_ack_in;

assign lbRequestPortOpenOut_TVALID = regslice_both_lbRequestPortOpenOut_U_vld_out;

assign lbRxDataIn_TREADY = regslice_both_lbRxDataIn_U_ack_in;

assign lbRxMetadataIn_TREADY = regslice_both_lbRxMetadataIn_U_ack_in;

assign message_offset_1_fu_1355_p2 = (zext_ln101_fu_1351_p1 + zext_ln47_fu_919_p1);

assign message_offset_fu_911_p3 = ((tmp_10_fu_885_p3[0:0] == 1'b1) ? select_ln63_2_fu_825_p3 : add_ln89_fu_899_p2);

assign metadata_to_book_TDATA_int_regslice = {{{{{{tmp_28_fu_394_p4}, {16'd0}}, {trunc_ln32_fu_370_p1}}, {tmp_27_fu_384_p4}}, {16'd0}}, {tmp_26_fu_374_p4}};

assign metadata_to_book_TVALID = regslice_both_metadata_to_book_U_vld_out;

assign or_ln101_1_fu_1309_p2 = (and_ln101_3_fu_1287_p2 | and_ln101_1_fu_1261_p2);

assign or_ln101_2_fu_1323_p2 = (tmp_12_fu_979_p3 | and_ln101_fu_1227_p2);

assign or_ln101_3_fu_1337_p2 = (or_ln101_2_fu_1323_p2 | or_ln101_1_fu_1309_p2);

assign or_ln101_fu_1241_p2 = (tmp_13_fu_991_p13 | orderID_buff_fu_951_p13);

assign or_ln106_1_fu_1113_p2 = (tmp_15_fu_1071_p13 | shl_ln106_1_fu_1107_p2);

assign or_ln106_2_fu_1185_p2 = (tmp_16_fu_1143_p13 | shl_ln106_2_fu_1179_p2);

assign or_ln106_fu_1033_p2 = (tmp_13_fu_991_p13 | shl_ln106_fu_1027_p2);

assign or_ln63_1_fu_769_p2 = (or_ln63_fu_763_p2 | encoded_message_3_fu_523_p4);

assign or_ln63_2_fu_803_p2 = (xor_ln63_1_fu_783_p2 | and_ln63_fu_797_p2);

assign or_ln63_fu_763_p2 = (encoded_message_7_fu_613_p4 | encoded_message_5_fu_573_p4);

assign or_ln76_2_fu_1449_p10 = {{{{{{{{{{{{{{{{1'd0}, {order_type_buff_fu_1405_p21}}}, {select_ln101_3_fu_1293_p3}}}, {tmp_17_fu_1361_p21}}}, {8'd0}}}, {size_buff_fu_905_p2}}}, {tmp_11_fu_923_p13}}}, {select_ln63_5_fu_849_p3}}}, {8'd0}};

assign or_ln_fu_755_p3 = {{tmp_4_fu_747_p3}, {trunc_ln42_3_fu_633_p4}};

assign orderID_buff_1_fu_1059_p3 = {{tmp_14_fu_1039_p4}, {or_ln106_fu_1033_p2}};

assign orderID_buff_2_fu_1129_p4 = {{{tmp_14_fu_1039_p4}, {tmp_20_fu_1119_p4}}, {or_ln106_1_fu_1113_p2}};

assign orderID_buff_3_fu_1201_p5 = {{{{trunc_ln_fu_1049_p4}, {tmp_20_fu_1119_p4}}, {tmp_21_fu_1191_p4}}, {or_ln106_2_fu_1185_p2}};

assign orderID_buff_fu_951_p11 = 'bx;

assign orderID_buff_fu_951_p2 = {{first_packet[39:32]}};

assign orderID_buff_fu_951_p4 = {{first_packet[47:40]}};

assign orderID_buff_fu_951_p6 = {{first_packet[55:48]}};

assign orderID_buff_fu_951_p8 = {{first_packet[63:56]}};

assign order_to_book_TDATA_int_regslice = or_ln76_2_fu_1449_p10;

assign order_to_book_TVALID = regslice_both_order_to_book_U_vld_out;

assign order_type_buff_fu_1405_p10 = {{second_packet[10:8]}};

assign order_type_buff_fu_1405_p12 = {{second_packet[18:16]}};

assign order_type_buff_fu_1405_p14 = {{second_packet[26:24]}};

assign order_type_buff_fu_1405_p16 = {{second_packet[34:32]}};

assign order_type_buff_fu_1405_p18 = {{second_packet[42:40]}};

assign order_type_buff_fu_1405_p19 = 'bx;

assign order_type_buff_fu_1405_p2 = {{first_packet[42:40]}};

assign order_type_buff_fu_1405_p4 = {{first_packet[50:48]}};

assign order_type_buff_fu_1405_p6 = {{first_packet[58:56]}};

assign order_type_buff_fu_1405_p8 = second_packet[2:0];

assign select_ln101_1_fu_1233_p3 = ((and_ln101_fu_1227_p2[0:0] == 1'b1) ? zext_ln48_fu_987_p1 : select_ln101_fu_1213_p3);

assign select_ln101_2_fu_1267_p3 = ((and_ln101_1_fu_1261_p2[0:0] == 1'b1) ? zext_ln48_1_fu_1067_p1 : select_ln101_1_fu_1233_p3);

assign select_ln101_3_fu_1293_p3 = ((and_ln101_3_fu_1287_p2[0:0] == 1'b1) ? zext_ln48_2_fu_1139_p1 : select_ln101_2_fu_1267_p3);

assign select_ln101_4_fu_1301_p3 = ((and_ln101_3_fu_1287_p2[0:0] == 1'b1) ? 3'd4 : 3'd3);

assign select_ln101_5_fu_1315_p3 = ((and_ln101_fu_1227_p2[0:0] == 1'b1) ? 3'd2 : 3'd1);

assign select_ln101_6_fu_1329_p3 = ((or_ln101_1_fu_1309_p2[0:0] == 1'b1) ? select_ln101_4_fu_1301_p3 : select_ln101_5_fu_1315_p3);

assign select_ln101_7_fu_1343_p3 = ((or_ln101_3_fu_1337_p2[0:0] == 1'b1) ? select_ln101_6_fu_1329_p3 : 3'd5);

assign select_ln101_fu_1213_p3 = ((tmp_12_fu_979_p3[0:0] == 1'b1) ? 25'd0 : orderID_buff_3_fu_1201_p5);

assign select_ln147_fu_356_p3 = ((grp_fu_326_p3[0:0] == 1'b1) ? 3'd4 : 3'd2);

assign select_ln50_fu_431_p3 = ((grp_fu_326_p3[0:0] == 1'b1) ? 3'd4 : 3'd3);

assign select_ln63_1_fu_817_p3 = ((and_ln63_fu_797_p2[0:0] == 1'b1) ? 3'd4 : 3'd6);

assign select_ln63_2_fu_825_p3 = ((or_ln63_2_fu_803_p2[0:0] == 1'b1) ? select_ln63_1_fu_817_p3 : select_ln63_fu_809_p3);

assign select_ln63_3_fu_833_p3 = ((and_ln63_fu_797_p2[0:0] == 1'b1) ? zext_ln58_fu_727_p1 : or_ln_fu_755_p3);

assign select_ln63_4_fu_841_p3 = ((tmp_2_fu_713_p3[0:0] == 1'b1) ? 8'd0 : decoded_mantissa_1_fu_739_p3);

assign select_ln63_5_fu_849_p3 = ((or_ln63_2_fu_803_p2[0:0] == 1'b1) ? select_ln63_3_fu_833_p3 : select_ln63_4_fu_841_p3);

assign select_ln63_fu_809_p3 = ((tmp_2_fu_713_p3[0:0] == 1'b1) ? 3'd3 : 3'd5);

assign shl_ln106_1_fu_1107_p2 = tmp_13_fu_991_p13 << 8'd7;

assign shl_ln106_2_fu_1179_p2 = tmp_15_fu_1071_p13 << 8'd7;

assign shl_ln106_fu_1027_p2 = orderID_buff_fu_951_p13 << 8'd7;

assign size_buff_fu_905_p2 = (xor_ln86_fu_893_p2 & trunc_ln86_fu_881_p1);

assign tagsIn_TREADY = regslice_both_tagsIn_U_ack_in;

assign time_to_book_TVALID = regslice_both_time_to_book_U_vld_out;

assign tmp_10_fu_885_p3 = tmp_7_fu_857_p11[32'd7];

assign tmp_11_fu_923_p10 = {{first_packet[62:56]}};

assign tmp_11_fu_923_p11 = 'bx;

assign tmp_11_fu_923_p2 = {{first_packet[30:24]}};

assign tmp_11_fu_923_p4 = {{first_packet[38:32]}};

assign tmp_11_fu_923_p6 = {{first_packet[46:40]}};

assign tmp_11_fu_923_p8 = {{first_packet[54:48]}};

assign tmp_12_fu_979_p3 = orderID_buff_fu_951_p13[32'd7];

assign tmp_13_fu_991_p10 = {{second_packet[15:8]}};

assign tmp_13_fu_991_p11 = 'bx;

assign tmp_13_fu_991_p2 = {{first_packet[47:40]}};

assign tmp_13_fu_991_p4 = {{first_packet[55:48]}};

assign tmp_13_fu_991_p6 = {{first_packet[63:56]}};

assign tmp_14_fu_1039_p4 = {{orderID_buff_fu_951_p13[7:1]}};

assign tmp_15_fu_1071_p10 = {{second_packet[23:16]}};

assign tmp_15_fu_1071_p11 = 'bx;

assign tmp_15_fu_1071_p2 = {{first_packet[55:48]}};

assign tmp_15_fu_1071_p4 = {{first_packet[63:56]}};

assign tmp_15_fu_1071_p8 = {{second_packet[15:8]}};

assign tmp_16_fu_1143_p10 = {{second_packet[31:24]}};

assign tmp_16_fu_1143_p11 = 'bx;

assign tmp_16_fu_1143_p2 = {{first_packet[63:56]}};

assign tmp_16_fu_1143_p6 = {{second_packet[15:8]}};

assign tmp_16_fu_1143_p8 = {{second_packet[23:16]}};

assign tmp_17_fu_1361_p10 = second_packet[6:0];

assign tmp_17_fu_1361_p12 = {{second_packet[14:8]}};

assign tmp_17_fu_1361_p14 = {{second_packet[22:16]}};

assign tmp_17_fu_1361_p16 = {{second_packet[30:24]}};

assign tmp_17_fu_1361_p18 = {{second_packet[38:32]}};

assign tmp_17_fu_1361_p19 = 'bx;

assign tmp_17_fu_1361_p2 = {{first_packet[38:32]}};

assign tmp_17_fu_1361_p4 = {{first_packet[46:40]}};

assign tmp_17_fu_1361_p6 = {{first_packet[54:48]}};

assign tmp_17_fu_1361_p8 = {{first_packet[62:56]}};

assign tmp_18_fu_1019_p3 = tmp_13_fu_991_p13[32'd7];

assign tmp_1_nbreadreq_fu_240_p3 = lbRxMetadataIn_TVALID_int_regslice;

assign tmp_20_fu_1119_p4 = {{or_ln106_fu_1033_p2[7:1]}};

assign tmp_21_fu_1191_p4 = {{or_ln106_1_fu_1113_p2[7:1]}};

assign tmp_22_fu_1099_p3 = tmp_15_fu_1071_p13[32'd7];

assign tmp_23_fu_1171_p3 = tmp_16_fu_1143_p13[32'd7];

assign tmp_24_fu_1247_p3 = or_ln101_fu_1241_p2[32'd7];

assign tmp_26_fu_374_p4 = {{lbRxMetadataIn_TDATA_int_regslice[79:64]}};

assign tmp_27_fu_384_p4 = {{lbRxMetadataIn_TDATA_int_regslice[127:96]}};

assign tmp_28_fu_394_p4 = {{lbRxMetadataIn_TDATA_int_regslice[63:32]}};

assign tmp_2_fu_713_p3 = first_packet[32'd31];

assign tmp_3_fu_731_p3 = first_packet[32'd24];

assign tmp_4_fu_747_p3 = first_packet[32'd32];

assign tmp_5_fu_775_p3 = or_ln63_1_fu_769_p2[32'd7];

assign tmp_6_fu_789_p3 = first_packet[32'd39];

assign tmp_7_fu_857_p2 = {{first_packet[31:24]}};

assign tmp_7_fu_857_p4 = {{first_packet[39:32]}};

assign tmp_7_fu_857_p6 = {{first_packet[47:40]}};

assign tmp_7_fu_857_p8 = {{first_packet[55:48]}};

assign tmp_7_fu_857_p9 = 'bx;

assign tmp_8_nbreadreq_fu_248_p3 = lbPortOpenReplyIn_TVALID_int_regslice;

assign trunc_ln145_fu_346_p1 = lbRxDataIn_TDATA_int_regslice[42:0];

assign trunc_ln32_fu_370_p1 = lbRxMetadataIn_TDATA_int_regslice[15:0];

assign trunc_ln41_fu_421_p1 = lbRxDataIn_TDATA_int_regslice[63:0];

assign trunc_ln42_3_fu_633_p4 = {{first_packet[46:40]}};

assign trunc_ln42_9_fu_583_p4 = {{first_packet[38:32]}};

assign trunc_ln86_fu_881_p1 = tmp_7_fu_857_p11[0:0];

assign trunc_ln_fu_1049_p4 = {{orderID_buff_fu_951_p13[3:1]}};

assign xor_ln101_1_fu_1275_p2 = (tmp_22_fu_1099_p3 ^ 1'd1);

assign xor_ln101_2_fu_1255_p2 = (tmp_24_fu_1247_p3 ^ 1'd1);

assign xor_ln101_fu_1221_p2 = (tmp_12_fu_979_p3 ^ 1'd1);

assign xor_ln63_1_fu_783_p2 = (tmp_5_fu_775_p3 ^ 1'd1);

assign xor_ln63_fu_721_p2 = (tmp_2_fu_713_p3 ^ 1'd1);

assign xor_ln86_fu_893_p2 = (tmp_10_fu_885_p3 ^ 1'd1);

assign zext_ln101_fu_1351_p1 = select_ln101_7_fu_1343_p3;

assign zext_ln47_fu_919_p1 = message_offset_fu_911_p3;

assign zext_ln48_1_fu_1067_p1 = orderID_buff_1_fu_1059_p3;

assign zext_ln48_2_fu_1139_p1 = orderID_buff_2_fu_1129_p4;

assign zext_ln48_fu_987_p1 = orderID_buff_fu_951_p13;

assign zext_ln58_fu_727_p1 = decoded_mantissa_fu_533_p4;

endmodule //Fast_processor_rxPath
