// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="Fast_processor_Fast_processor,hls_ip_2023_2_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xcku5p-ffvb676-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=dataflow,HLS_SYN_CLOCK=5.149000,HLS_SYN_LAT=5,HLS_SYN_TPT=4,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=253,HLS_SYN_LUT=997,HLS_VERSION=2023_2_1}" *)

module Fast_processor (
        lbRxDataIn_TDATA,
        lbRxMetadataIn_TDATA,
        lbRequestPortOpenOut_TDATA,
        lbPortOpenReplyIn_TDATA,
        lbTxDataOut_TDATA,
        lbTxMetadataOut_TDATA,
        lbTxLengthOut_TDATA,
        tagsIn_TDATA,
        tagsOut_TDATA,
        metadata_to_book_TDATA,
        metadata_from_book_TDATA,
        time_to_book_TDATA,
        time_from_book_TDATA,
        order_to_book_TDATA,
        order_from_book_TDATA,
        ap_clk,
        ap_rst_n,
        lbRxDataIn_TVALID,
        lbRxDataIn_TREADY,
        lbRxMetadataIn_TVALID,
        lbRxMetadataIn_TREADY,
        lbRequestPortOpenOut_TVALID,
        lbRequestPortOpenOut_TREADY,
        lbPortOpenReplyIn_TVALID,
        lbPortOpenReplyIn_TREADY,
        metadata_to_book_TVALID,
        metadata_to_book_TREADY,
        tagsIn_TVALID,
        tagsIn_TREADY,
        time_to_book_TVALID,
        time_to_book_TREADY,
        order_to_book_TVALID,
        order_to_book_TREADY,
        metadata_from_book_TVALID,
        metadata_from_book_TREADY,
        lbTxDataOut_TVALID,
        lbTxDataOut_TREADY,
        lbTxMetadataOut_TVALID,
        lbTxMetadataOut_TREADY,
        lbTxLengthOut_TVALID,
        lbTxLengthOut_TREADY,
        time_from_book_TVALID,
        time_from_book_TREADY,
        tagsOut_TVALID,
        tagsOut_TREADY,
        order_from_book_TVALID,
        order_from_book_TREADY
);


input  [127:0] lbRxDataIn_TDATA;
input  [127:0] lbRxMetadataIn_TDATA;
output  [15:0] lbRequestPortOpenOut_TDATA;
input  [7:0] lbPortOpenReplyIn_TDATA;
output  [127:0] lbTxDataOut_TDATA;
output  [127:0] lbTxMetadataOut_TDATA;
output  [15:0] lbTxLengthOut_TDATA;
input  [63:0] tagsIn_TDATA;
output  [63:0] tagsOut_TDATA;
output  [127:0] metadata_to_book_TDATA;
input  [127:0] metadata_from_book_TDATA;
output  [63:0] time_to_book_TDATA;
input  [63:0] time_from_book_TDATA;
output  [95:0] order_to_book_TDATA;
input  [95:0] order_from_book_TDATA;
input   ap_clk;
input   ap_rst_n;
input   lbRxDataIn_TVALID;
output   lbRxDataIn_TREADY;
input   lbRxMetadataIn_TVALID;
output   lbRxMetadataIn_TREADY;
output   lbRequestPortOpenOut_TVALID;
input   lbRequestPortOpenOut_TREADY;
input   lbPortOpenReplyIn_TVALID;
output   lbPortOpenReplyIn_TREADY;
output   metadata_to_book_TVALID;
input   metadata_to_book_TREADY;
input   tagsIn_TVALID;
output   tagsIn_TREADY;
output   time_to_book_TVALID;
input   time_to_book_TREADY;
output   order_to_book_TVALID;
input   order_to_book_TREADY;
input   metadata_from_book_TVALID;
output   metadata_from_book_TREADY;
output   lbTxDataOut_TVALID;
input   lbTxDataOut_TREADY;
output   lbTxMetadataOut_TVALID;
input   lbTxMetadataOut_TREADY;
output   lbTxLengthOut_TVALID;
input   lbTxLengthOut_TREADY;
input   time_from_book_TVALID;
output   time_from_book_TREADY;
output   tagsOut_TVALID;
input   tagsOut_TREADY;
input   order_from_book_TVALID;
output   order_from_book_TREADY;

 reg    ap_rst_n_inv;
wire    rxPath_U0_ap_start;
wire    rxPath_U0_ap_done;
wire    rxPath_U0_ap_continue;
wire    rxPath_U0_ap_idle;
wire    rxPath_U0_ap_ready;
wire    rxPath_U0_lbRxDataIn_TREADY;
wire    rxPath_U0_lbRxMetadataIn_TREADY;
wire   [15:0] rxPath_U0_lbRequestPortOpenOut_TDATA;
wire    rxPath_U0_lbRequestPortOpenOut_TVALID;
wire    rxPath_U0_lbPortOpenReplyIn_TREADY;
wire   [127:0] rxPath_U0_metadata_to_book_TDATA;
wire    rxPath_U0_metadata_to_book_TVALID;
wire    rxPath_U0_tagsIn_TREADY;
wire   [63:0] rxPath_U0_time_to_book_TDATA;
wire    rxPath_U0_time_to_book_TVALID;
wire   [95:0] rxPath_U0_order_to_book_TDATA;
wire    rxPath_U0_order_to_book_TVALID;
wire    txPath_U0_ap_start;
wire    txPath_U0_ap_done;
wire    txPath_U0_ap_continue;
wire    txPath_U0_ap_idle;
wire    txPath_U0_ap_ready;
wire    txPath_U0_metadata_from_book_TREADY;
wire   [127:0] txPath_U0_lbTxDataOut_TDATA;
wire    txPath_U0_lbTxDataOut_TVALID;
wire   [127:0] txPath_U0_lbTxMetadataOut_TDATA;
wire    txPath_U0_lbTxMetadataOut_TVALID;
wire   [15:0] txPath_U0_lbTxLengthOut_TDATA;
wire    txPath_U0_lbTxLengthOut_TVALID;
wire    txPath_U0_time_from_book_TREADY;
wire   [63:0] txPath_U0_tagsOut_TDATA;
wire    txPath_U0_tagsOut_TVALID;
wire    txPath_U0_order_from_book_TREADY;

Fast_processor_rxPath rxPath_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(rxPath_U0_ap_start),
    .ap_done(rxPath_U0_ap_done),
    .ap_continue(rxPath_U0_ap_continue),
    .ap_idle(rxPath_U0_ap_idle),
    .ap_ready(rxPath_U0_ap_ready),
    .lbRxDataIn_TVALID(lbRxDataIn_TVALID),
    .tagsIn_TVALID(tagsIn_TVALID),
    .time_to_book_TREADY(time_to_book_TREADY),
    .lbRxMetadataIn_TVALID(lbRxMetadataIn_TVALID),
    .metadata_to_book_TREADY(metadata_to_book_TREADY),
    .lbPortOpenReplyIn_TVALID(lbPortOpenReplyIn_TVALID),
    .order_to_book_TREADY(order_to_book_TREADY),
    .lbRequestPortOpenOut_TREADY(lbRequestPortOpenOut_TREADY),
    .lbRxDataIn_TDATA(lbRxDataIn_TDATA),
    .lbRxDataIn_TREADY(rxPath_U0_lbRxDataIn_TREADY),
    .lbRxMetadataIn_TDATA(lbRxMetadataIn_TDATA),
    .lbRxMetadataIn_TREADY(rxPath_U0_lbRxMetadataIn_TREADY),
    .lbRequestPortOpenOut_TDATA(rxPath_U0_lbRequestPortOpenOut_TDATA),
    .lbRequestPortOpenOut_TVALID(rxPath_U0_lbRequestPortOpenOut_TVALID),
    .lbPortOpenReplyIn_TDATA(lbPortOpenReplyIn_TDATA),
    .lbPortOpenReplyIn_TREADY(rxPath_U0_lbPortOpenReplyIn_TREADY),
    .metadata_to_book_TDATA(rxPath_U0_metadata_to_book_TDATA),
    .metadata_to_book_TVALID(rxPath_U0_metadata_to_book_TVALID),
    .tagsIn_TDATA(tagsIn_TDATA),
    .tagsIn_TREADY(rxPath_U0_tagsIn_TREADY),
    .time_to_book_TDATA(rxPath_U0_time_to_book_TDATA),
    .time_to_book_TVALID(rxPath_U0_time_to_book_TVALID),
    .order_to_book_TDATA(rxPath_U0_order_to_book_TDATA),
    .order_to_book_TVALID(rxPath_U0_order_to_book_TVALID)
);

Fast_processor_txPath txPath_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(txPath_U0_ap_start),
    .ap_done(txPath_U0_ap_done),
    .ap_continue(txPath_U0_ap_continue),
    .ap_idle(txPath_U0_ap_idle),
    .ap_ready(txPath_U0_ap_ready),
    .time_from_book_TVALID(time_from_book_TVALID),
    .metadata_from_book_TVALID(metadata_from_book_TVALID),
    .lbTxMetadataOut_TREADY(lbTxMetadataOut_TREADY),
    .order_from_book_TVALID(order_from_book_TVALID),
    .lbTxDataOut_TREADY(lbTxDataOut_TREADY),
    .lbTxLengthOut_TREADY(lbTxLengthOut_TREADY),
    .tagsOut_TREADY(tagsOut_TREADY),
    .metadata_from_book_TDATA(metadata_from_book_TDATA),
    .metadata_from_book_TREADY(txPath_U0_metadata_from_book_TREADY),
    .lbTxDataOut_TDATA(txPath_U0_lbTxDataOut_TDATA),
    .lbTxDataOut_TVALID(txPath_U0_lbTxDataOut_TVALID),
    .lbTxMetadataOut_TDATA(txPath_U0_lbTxMetadataOut_TDATA),
    .lbTxMetadataOut_TVALID(txPath_U0_lbTxMetadataOut_TVALID),
    .lbTxLengthOut_TDATA(txPath_U0_lbTxLengthOut_TDATA),
    .lbTxLengthOut_TVALID(txPath_U0_lbTxLengthOut_TVALID),
    .time_from_book_TDATA(time_from_book_TDATA),
    .time_from_book_TREADY(txPath_U0_time_from_book_TREADY),
    .tagsOut_TDATA(txPath_U0_tagsOut_TDATA),
    .tagsOut_TVALID(txPath_U0_tagsOut_TVALID),
    .order_from_book_TDATA(order_from_book_TDATA),
    .order_from_book_TREADY(txPath_U0_order_from_book_TREADY)
);

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign lbPortOpenReplyIn_TREADY = rxPath_U0_lbPortOpenReplyIn_TREADY;

assign lbRequestPortOpenOut_TDATA = rxPath_U0_lbRequestPortOpenOut_TDATA;

assign lbRequestPortOpenOut_TVALID = rxPath_U0_lbRequestPortOpenOut_TVALID;

assign lbRxDataIn_TREADY = rxPath_U0_lbRxDataIn_TREADY;

assign lbRxMetadataIn_TREADY = rxPath_U0_lbRxMetadataIn_TREADY;

assign lbTxDataOut_TDATA = txPath_U0_lbTxDataOut_TDATA;

assign lbTxDataOut_TVALID = txPath_U0_lbTxDataOut_TVALID;

assign lbTxLengthOut_TDATA = txPath_U0_lbTxLengthOut_TDATA;

assign lbTxLengthOut_TVALID = txPath_U0_lbTxLengthOut_TVALID;

assign lbTxMetadataOut_TDATA = txPath_U0_lbTxMetadataOut_TDATA;

assign lbTxMetadataOut_TVALID = txPath_U0_lbTxMetadataOut_TVALID;

assign metadata_from_book_TREADY = txPath_U0_metadata_from_book_TREADY;

assign metadata_to_book_TDATA = rxPath_U0_metadata_to_book_TDATA;

assign metadata_to_book_TVALID = rxPath_U0_metadata_to_book_TVALID;

assign order_from_book_TREADY = txPath_U0_order_from_book_TREADY;

assign order_to_book_TDATA = rxPath_U0_order_to_book_TDATA;

assign order_to_book_TVALID = rxPath_U0_order_to_book_TVALID;

assign rxPath_U0_ap_continue = 1'b1;

assign rxPath_U0_ap_start = 1'b1;

assign tagsIn_TREADY = rxPath_U0_tagsIn_TREADY;

assign tagsOut_TDATA = txPath_U0_tagsOut_TDATA;

assign tagsOut_TVALID = txPath_U0_tagsOut_TVALID;

assign time_from_book_TREADY = txPath_U0_time_from_book_TREADY;

assign time_to_book_TDATA = rxPath_U0_time_to_book_TDATA;

assign time_to_book_TVALID = rxPath_U0_time_to_book_TVALID;

assign txPath_U0_ap_continue = 1'b1;

assign txPath_U0_ap_start = 1'b1;

endmodule //Fast_processor
