// ==============================================================
// Generated by Vitis HLS v2023.2.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module Fast_processor_txPath (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        time_from_book_TVALID,
        metadata_from_book_TVALID,
        lbTxMetadataOut_TREADY,
        order_from_book_TVALID,
        lbTxDataOut_TREADY,
        lbTxLengthOut_TREADY,
        tagsOut_TREADY,
        metadata_from_book_TDATA,
        metadata_from_book_TREADY,
        lbTxDataOut_TDATA,
        lbTxDataOut_TVALID,
        lbTxMetadataOut_TDATA,
        lbTxMetadataOut_TVALID,
        lbTxLengthOut_TDATA,
        lbTxLengthOut_TVALID,
        time_from_book_TDATA,
        time_from_book_TREADY,
        tagsOut_TDATA,
        tagsOut_TVALID,
        order_from_book_TDATA,
        order_from_book_TREADY
);

parameter    ap_ST_iter0_fsm_state1 = 4'd1;
parameter    ap_ST_iter0_fsm_state2 = 4'd4;
parameter    ap_ST_iter0_fsm_state3 = 4'd8;
parameter    ap_ST_iter1_fsm_state4 = 3'd2;
parameter    ap_ST_iter1_fsm_state5 = 3'd4;
parameter    ap_ST_iter0_fsm_state6 = 4'd2;
parameter    ap_ST_iter1_fsm_state0 = 3'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input   time_from_book_TVALID;
input   metadata_from_book_TVALID;
input   lbTxMetadataOut_TREADY;
input   order_from_book_TVALID;
input   lbTxDataOut_TREADY;
input   lbTxLengthOut_TREADY;
input   tagsOut_TREADY;
input  [127:0] metadata_from_book_TDATA;
output   metadata_from_book_TREADY;
output  [127:0] lbTxDataOut_TDATA;
output   lbTxDataOut_TVALID;
output  [127:0] lbTxMetadataOut_TDATA;
output   lbTxMetadataOut_TVALID;
output  [15:0] lbTxLengthOut_TDATA;
output   lbTxLengthOut_TVALID;
input  [63:0] time_from_book_TDATA;
output   time_from_book_TREADY;
output  [63:0] tagsOut_TDATA;
output   tagsOut_TVALID;
input  [95:0] order_from_book_TDATA;
output   order_from_book_TREADY;

reg ap_done;
reg ap_idle;
reg ap_ready;

reg   [3:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
reg   [2:0] ap_CS_iter1_fsm;
wire    ap_CS_iter1_fsm_state0;
wire    ap_CS_iter0_fsm_state3;
reg   [1:0] next_state_load_reg_232;
reg   [0:0] tmp_reg_236;
reg   [0:0] tmp_3_reg_240;
reg   [0:0] tmp_4_reg_244;
reg   [0:0] tmp_5_reg_279;
reg   [0:0] tmp_6_reg_248;
wire   [0:0] grp_nbwritereq_fu_116_p3;
reg    ap_predicate_op37_read_state3;
reg    ap_predicate_op38_read_state3;
reg    ap_predicate_op39_write_state3;
reg    ap_predicate_op40_read_state3;
reg    ap_block_state3_pp0_stage3_iter0;
reg    ap_block_state3_io;
reg   [1:0] next_state_load_reg_232_pp0_iter0_reg;
reg   [0:0] tmp_1_reg_252;
reg    ap_predicate_op43_write_state4;
reg   [0:0] tmp_2_reg_256;
reg    ap_predicate_op48_write_state4;
reg    ap_predicate_op49_write_state4;
reg   [0:0] tmp_reg_236_pp0_iter0_reg;
reg   [0:0] tmp_3_reg_240_pp0_iter0_reg;
reg   [0:0] tmp_4_reg_244_pp0_iter0_reg;
reg   [0:0] tmp_5_reg_279_pp0_iter0_reg;
reg   [0:0] tmp_6_reg_248_pp0_iter0_reg;
reg   [0:0] tmp_7_reg_260;
reg    ap_predicate_op50_write_state4;
reg    ap_predicate_op51_write_state4;
reg    ap_block_state4_pp0_stage0_iter1;
reg    ap_block_state4_io;
wire    ap_CS_iter1_fsm_state4;
reg    ap_predicate_op52_write_state5;
reg    ap_predicate_op55_write_state5;
reg    ap_predicate_op56_write_state5;
reg    ap_predicate_op59_write_state5;
wire    regslice_both_lbTxDataOut_U_apdone_blk;
wire    regslice_both_lbTxMetadataOut_U_apdone_blk;
wire    regslice_both_lbTxLengthOut_U_apdone_blk;
wire    regslice_both_tagsOut_U_apdone_blk;
reg    ap_block_state5_pp0_stage1_iter1;
reg    ap_block_state5_io;
wire    ap_CS_iter1_fsm_state5;
reg    ap_done_reg;
reg   [1:0] next_state;
reg   [0:0] second_packet_last;
reg    metadata_from_book_TDATA_blk_n;
reg    lbTxDataOut_TDATA_blk_n;
reg    lbTxMetadataOut_TDATA_blk_n;
reg    lbTxLengthOut_TDATA_blk_n;
reg    time_from_book_TDATA_blk_n;
reg    tagsOut_TDATA_blk_n;
reg    order_from_book_TDATA_blk_n;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] tmp_nbreadreq_fu_76_p3;
wire   [0:0] tmp_3_nbreadreq_fu_84_p3;
wire   [0:0] tmp_4_nbreadreq_fu_92_p3;
wire    ap_CS_iter0_fsm_state2;
wire   [0:0] grp_nbwritereq_fu_108_p3;
reg   [63:0] time_from_book_read_reg_264;
wire   [127:0] zext_ln215_fu_227_p1;
wire    ap_CS_iter0_fsm_state6;
wire   [72:0] shl_ln_fu_213_p3;
wire   [72:0] or_ln215_fu_221_p2;
reg   [3:0] ap_NS_iter0_fsm;
reg   [2:0] ap_NS_iter1_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter0_fsm_state2_blk;
reg    ap_ST_iter0_fsm_state3_blk;
reg    ap_ST_iter1_fsm_state4_blk;
reg    ap_ST_iter1_fsm_state5_blk;
wire    ap_ST_iter0_fsm_state6_blk;
wire    regslice_both_metadata_from_book_U_apdone_blk;
wire   [127:0] metadata_from_book_TDATA_int_regslice;
wire    metadata_from_book_TVALID_int_regslice;
reg    metadata_from_book_TREADY_int_regslice;
wire    regslice_both_metadata_from_book_U_ack_in;
reg   [127:0] lbTxDataOut_TDATA_int_regslice;
reg    lbTxDataOut_TVALID_int_regslice;
wire    lbTxDataOut_TREADY_int_regslice;
wire    regslice_both_lbTxDataOut_U_vld_out;
reg    lbTxMetadataOut_TVALID_int_regslice;
wire    lbTxMetadataOut_TREADY_int_regslice;
wire    regslice_both_lbTxMetadataOut_U_vld_out;
reg    lbTxLengthOut_TVALID_int_regslice;
wire    lbTxLengthOut_TREADY_int_regslice;
wire    regslice_both_lbTxLengthOut_U_vld_out;
wire    regslice_both_time_from_book_U_apdone_blk;
wire   [63:0] time_from_book_TDATA_int_regslice;
wire    time_from_book_TVALID_int_regslice;
reg    time_from_book_TREADY_int_regslice;
wire    regslice_both_time_from_book_U_ack_in;
reg    tagsOut_TVALID_int_regslice;
wire    tagsOut_TREADY_int_regslice;
wire    regslice_both_tagsOut_U_vld_out;
wire    regslice_both_order_from_book_U_apdone_blk;
wire   [95:0] order_from_book_TDATA_int_regslice;
wire    order_from_book_TVALID_int_regslice;
reg    order_from_book_TREADY_int_regslice;
wire    regslice_both_order_from_book_U_ack_in;
reg    ap_condition_332;
reg    ap_condition_68;
reg    ap_condition_208;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 4'd1;
#0 ap_CS_iter1_fsm = 3'd1;
#0 ap_done_reg = 1'b0;
#0 next_state = 2'd0;
#0 second_packet_last = 1'd0;
end

Fast_processor_regslice_both #(
    .DataWidth( 128 ))
regslice_both_metadata_from_book_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(metadata_from_book_TDATA),
    .vld_in(metadata_from_book_TVALID),
    .ack_in(regslice_both_metadata_from_book_U_ack_in),
    .data_out(metadata_from_book_TDATA_int_regslice),
    .vld_out(metadata_from_book_TVALID_int_regslice),
    .ack_out(metadata_from_book_TREADY_int_regslice),
    .apdone_blk(regslice_both_metadata_from_book_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 128 ))
regslice_both_lbTxDataOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(lbTxDataOut_TDATA_int_regslice),
    .vld_in(lbTxDataOut_TVALID_int_regslice),
    .ack_in(lbTxDataOut_TREADY_int_regslice),
    .data_out(lbTxDataOut_TDATA),
    .vld_out(regslice_both_lbTxDataOut_U_vld_out),
    .ack_out(lbTxDataOut_TREADY),
    .apdone_blk(regslice_both_lbTxDataOut_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 128 ))
regslice_both_lbTxMetadataOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(metadata_from_book_TDATA_int_regslice),
    .vld_in(lbTxMetadataOut_TVALID_int_regslice),
    .ack_in(lbTxMetadataOut_TREADY_int_regslice),
    .data_out(lbTxMetadataOut_TDATA),
    .vld_out(regslice_both_lbTxMetadataOut_U_vld_out),
    .ack_out(lbTxMetadataOut_TREADY),
    .apdone_blk(regslice_both_lbTxMetadataOut_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 16 ))
regslice_both_lbTxLengthOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(16'd128),
    .vld_in(lbTxLengthOut_TVALID_int_regslice),
    .ack_in(lbTxLengthOut_TREADY_int_regslice),
    .data_out(lbTxLengthOut_TDATA),
    .vld_out(regslice_both_lbTxLengthOut_U_vld_out),
    .ack_out(lbTxLengthOut_TREADY),
    .apdone_blk(regslice_both_lbTxLengthOut_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 64 ))
regslice_both_time_from_book_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(time_from_book_TDATA),
    .vld_in(time_from_book_TVALID),
    .ack_in(regslice_both_time_from_book_U_ack_in),
    .data_out(time_from_book_TDATA_int_regslice),
    .vld_out(time_from_book_TVALID_int_regslice),
    .ack_out(time_from_book_TREADY_int_regslice),
    .apdone_blk(regslice_both_time_from_book_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 64 ))
regslice_both_tagsOut_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(time_from_book_read_reg_264),
    .vld_in(tagsOut_TVALID_int_regslice),
    .ack_in(tagsOut_TREADY_int_regslice),
    .data_out(tagsOut_TDATA),
    .vld_out(regslice_both_tagsOut_U_vld_out),
    .ack_out(tagsOut_TREADY),
    .apdone_blk(regslice_both_tagsOut_U_apdone_blk)
);

Fast_processor_regslice_both #(
    .DataWidth( 96 ))
regslice_both_order_from_book_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .data_in(order_from_book_TDATA),
    .vld_in(order_from_book_TVALID),
    .ack_in(regslice_both_order_from_book_U_ack_in),
    .data_out(order_from_book_TDATA_int_regslice),
    .vld_out(order_from_book_TVALID_int_regslice),
    .ack_out(order_from_book_TREADY_int_regslice),
    .apdone_blk(regslice_both_order_from_book_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state5))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_208)) begin
        if ((1'b1 == ap_condition_68)) begin
            next_state <= 2'd1;
        end else if (((next_state_load_reg_232 == 2'd2) & (grp_nbwritereq_fu_108_p3 == 1'd1))) begin
            next_state <= 2'd0;
        end else if (((next_state_load_reg_232 == 2'd1) & (grp_nbwritereq_fu_108_p3 == 1'd1))) begin
            next_state <= 2'd2;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        next_state_load_reg_232 <= next_state;
        tmp_3_reg_240 <= tmp_3_nbreadreq_fu_84_p3;
        tmp_4_reg_244 <= tmp_4_nbreadreq_fu_92_p3;
        tmp_reg_236 <= tmp_nbreadreq_fu_76_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        next_state_load_reg_232_pp0_iter0_reg <= next_state_load_reg_232;
        time_from_book_read_reg_264 <= time_from_book_TDATA_int_regslice;
        tmp_1_reg_252 <= lbTxDataOut_TREADY_int_regslice;
        tmp_2_reg_256 <= lbTxDataOut_TREADY_int_regslice;
        tmp_3_reg_240_pp0_iter0_reg <= tmp_3_reg_240;
        tmp_4_reg_244_pp0_iter0_reg <= tmp_4_reg_244;
        tmp_5_reg_279_pp0_iter0_reg <= tmp_5_reg_279;
        tmp_6_reg_248_pp0_iter0_reg <= tmp_6_reg_248;
        tmp_7_reg_260 <= tagsOut_TREADY_int_regslice;
        tmp_reg_236_pp0_iter0_reg <= tmp_reg_236;
    end
end

always @ (posedge ap_clk) begin
    if ((~(next_state_load_reg_232 == 2'd1) & ~(next_state_load_reg_232 == 2'd2) & ~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (grp_nbwritereq_fu_116_p3 == 1'd1) & (tmp_6_reg_248 == 1'd1) & (tmp_5_reg_279 == 1'd1) & (tmp_4_reg_244 == 1'd1) & (tmp_3_reg_240 == 1'd1) & (tmp_reg_236 == 1'd1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        second_packet_last <= 1'd1;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state6))) begin
        tmp_5_reg_279 <= lbTxMetadataOut_TREADY_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
        tmp_6_reg_248 <= lbTxLengthOut_TREADY_int_regslice;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter0_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0))) begin
        ap_ST_iter0_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_iter0_fsm_state6_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1))) begin
        ap_ST_iter1_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) begin
        ap_ST_iter1_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state5))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter1_fsm_state0) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state5) & (ap_predicate_op55_write_state5 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state5) & (ap_predicate_op52_write_state5 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op48_write_state4 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op43_write_state4 == 1'b1)))) begin
        lbTxDataOut_TDATA_blk_n = lbTxDataOut_TREADY_int_regslice;
    end else begin
        lbTxDataOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((1'b1 == ap_condition_332)) begin
        if ((ap_predicate_op48_write_state4 == 1'b1)) begin
            lbTxDataOut_TDATA_int_regslice = zext_ln215_fu_227_p1;
        end else if ((ap_predicate_op43_write_state4 == 1'b1)) begin
            lbTxDataOut_TDATA_int_regslice = 128'd4703919738795935662080;
        end else begin
            lbTxDataOut_TDATA_int_regslice = 'bx;
        end
    end else begin
        lbTxDataOut_TDATA_int_regslice = 'bx;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op48_write_state4 == 1'b1)) | (~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op43_write_state4 == 1'b1)))) begin
        lbTxDataOut_TVALID_int_regslice = 1'b1;
    end else begin
        lbTxDataOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state5) & (ap_predicate_op56_write_state5 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op49_write_state4 == 1'b1)))) begin
        lbTxLengthOut_TDATA_blk_n = lbTxLengthOut_TREADY_int_regslice;
    end else begin
        lbTxLengthOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op49_write_state4 == 1'b1))) begin
        lbTxLengthOut_TVALID_int_regslice = 1'b1;
    end else begin
        lbTxLengthOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_predicate_op39_write_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3)) | ((1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op51_write_state4 == 1'b1)))) begin
        lbTxMetadataOut_TDATA_blk_n = lbTxMetadataOut_TREADY_int_regslice;
    end else begin
        lbTxMetadataOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (ap_predicate_op39_write_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        lbTxMetadataOut_TVALID_int_regslice = 1'b1;
    end else begin
        lbTxMetadataOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op38_read_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        metadata_from_book_TDATA_blk_n = metadata_from_book_TVALID_int_regslice;
    end else begin
        metadata_from_book_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (ap_predicate_op38_read_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        metadata_from_book_TREADY_int_regslice = 1'b1;
    end else begin
        metadata_from_book_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op40_read_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        order_from_book_TDATA_blk_n = order_from_book_TVALID_int_regslice;
    end else begin
        order_from_book_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (ap_predicate_op40_read_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        order_from_book_TREADY_int_regslice = 1'b1;
    end else begin
        order_from_book_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter1_fsm_state5) & (ap_predicate_op59_write_state5 == 1'b1)) | ((1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op50_write_state4 == 1'b1)))) begin
        tagsOut_TDATA_blk_n = tagsOut_TREADY_int_regslice;
    end else begin
        tagsOut_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state4) & (ap_predicate_op50_write_state4 == 1'b1))) begin
        tagsOut_TVALID_int_regslice = 1'b1;
    end else begin
        tagsOut_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((ap_predicate_op37_read_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        time_from_book_TDATA_blk_n = time_from_book_TVALID_int_regslice;
    end else begin
        time_from_book_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (ap_predicate_op37_read_state3 == 1'b1) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
        time_from_book_TREADY_int_regslice = 1'b1;
    end else begin
        time_from_book_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            if ((~((1'b1 == ap_block_state1_pp0_stage0_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state6;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end
        end
        ap_ST_iter0_fsm_state2 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state2))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state3;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end
        end
        ap_ST_iter0_fsm_state3 : begin
            if (~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1))))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state3;
            end
        end
        ap_ST_iter0_fsm_state6 : begin
            if ((~((ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state6))) begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state2;
            end else begin
                ap_NS_iter0_fsm = ap_ST_iter0_fsm_state6;
            end
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state4 : begin
            if ((~((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state4))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state5;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state4;
            end
        end
        ap_ST_iter1_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0)) & ~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state4;
            end else if ((~((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1) | (ap_done_reg == 1'b1)) & ((1'b0 == ap_CS_iter0_fsm_state3) | ((1'b1 == ap_CS_iter0_fsm_state3) & ((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0)))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state5;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state3))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state4;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter0_fsm_state2 = ap_CS_iter0_fsm[32'd2];

assign ap_CS_iter0_fsm_state3 = ap_CS_iter0_fsm[32'd3];

assign ap_CS_iter0_fsm_state6 = ap_CS_iter0_fsm[32'd1];

assign ap_CS_iter1_fsm_state0 = ap_CS_iter1_fsm[32'd0];

assign ap_CS_iter1_fsm_state4 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter1_fsm_state5 = ap_CS_iter1_fsm[32'd2];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_done_reg == 1'b1) | (ap_start == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((ap_predicate_op39_write_state3 == 1'b1) & (lbTxMetadataOut_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage3_iter0 = (((ap_predicate_op40_read_state3 == 1'b1) & (order_from_book_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op39_write_state3 == 1'b1) & (lbTxMetadataOut_TREADY_int_regslice == 1'b0)) | ((ap_predicate_op38_read_state3 == 1'b1) & (metadata_from_book_TVALID_int_regslice == 1'b0)) | ((ap_predicate_op37_read_state3 == 1'b1) & (time_from_book_TVALID_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_block_state4_io = (((tagsOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op50_write_state4 == 1'b1)) | ((lbTxLengthOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op49_write_state4 == 1'b1)) | ((lbTxMetadataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op51_write_state4 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op48_write_state4 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op43_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter1 = (((tagsOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op50_write_state4 == 1'b1)) | ((lbTxLengthOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op49_write_state4 == 1'b1)) | ((lbTxMetadataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op51_write_state4 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op48_write_state4 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op43_write_state4 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_io = (((tagsOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state5 == 1'b1)) | ((lbTxLengthOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op56_write_state5 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state5 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op52_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_block_state5_pp0_stage1_iter1 = ((regslice_both_tagsOut_U_apdone_blk == 1'b1) | (regslice_both_lbTxLengthOut_U_apdone_blk == 1'b1) | (regslice_both_lbTxMetadataOut_U_apdone_blk == 1'b1) | (regslice_both_lbTxDataOut_U_apdone_blk == 1'b1) | ((tagsOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op59_write_state5 == 1'b1)) | ((lbTxLengthOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op56_write_state5 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state5 == 1'b1)) | ((lbTxDataOut_TREADY_int_regslice == 1'b0) & (ap_predicate_op52_write_state5 == 1'b1)));
end

always @ (*) begin
    ap_condition_208 = (~((1'b1 == ap_block_state3_io) | (1'b1 == ap_block_state3_pp0_stage3_iter0) | (ap_done_reg == 1'b1) | ((1'b1 == ap_CS_iter1_fsm_state5) & ((1'b1 == ap_block_state5_io) | (1'b1 == ap_block_state5_pp0_stage1_iter1))) | ((1'b1 == ap_CS_iter1_fsm_state4) & ((1'b1 == ap_block_state4_io) | (1'b1 == ap_block_state4_pp0_stage0_iter1)))) & (1'b1 == ap_CS_iter0_fsm_state3));
end

always @ (*) begin
    ap_condition_332 = (~((1'b1 == ap_block_state4_pp0_stage0_iter1) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_iter1_fsm_state4));
end

always @ (*) begin
    ap_condition_68 = (~(next_state_load_reg_232 == 2'd1) & ~(next_state_load_reg_232 == 2'd2) & (grp_nbwritereq_fu_116_p3 == 1'd1) & (tmp_6_reg_248 == 1'd1) & (tmp_5_reg_279 == 1'd1) & (tmp_4_reg_244 == 1'd1) & (tmp_3_reg_240 == 1'd1) & (tmp_reg_236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op37_read_state3 = (~(next_state_load_reg_232 == 2'd1) & ~(next_state_load_reg_232 == 2'd2) & (grp_nbwritereq_fu_116_p3 == 1'd1) & (tmp_6_reg_248 == 1'd1) & (tmp_5_reg_279 == 1'd1) & (tmp_4_reg_244 == 1'd1) & (tmp_3_reg_240 == 1'd1) & (tmp_reg_236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op38_read_state3 = (~(next_state_load_reg_232 == 2'd1) & ~(next_state_load_reg_232 == 2'd2) & (grp_nbwritereq_fu_116_p3 == 1'd1) & (tmp_6_reg_248 == 1'd1) & (tmp_5_reg_279 == 1'd1) & (tmp_4_reg_244 == 1'd1) & (tmp_3_reg_240 == 1'd1) & (tmp_reg_236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op39_write_state3 = (~(next_state_load_reg_232 == 2'd1) & ~(next_state_load_reg_232 == 2'd2) & (grp_nbwritereq_fu_116_p3 == 1'd1) & (tmp_6_reg_248 == 1'd1) & (tmp_5_reg_279 == 1'd1) & (tmp_4_reg_244 == 1'd1) & (tmp_3_reg_240 == 1'd1) & (tmp_reg_236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op40_read_state3 = (~(next_state_load_reg_232 == 2'd1) & ~(next_state_load_reg_232 == 2'd2) & (grp_nbwritereq_fu_116_p3 == 1'd1) & (tmp_6_reg_248 == 1'd1) & (tmp_5_reg_279 == 1'd1) & (tmp_4_reg_244 == 1'd1) & (tmp_3_reg_240 == 1'd1) & (tmp_reg_236 == 1'd1));
end

always @ (*) begin
    ap_predicate_op43_write_state4 = ((next_state_load_reg_232_pp0_iter0_reg == 2'd1) & (tmp_1_reg_252 == 1'd1));
end

always @ (*) begin
    ap_predicate_op48_write_state4 = ((next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_2_reg_256 == 1'd1));
end

always @ (*) begin
    ap_predicate_op49_write_state4 = ((next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_2_reg_256 == 1'd1));
end

always @ (*) begin
    ap_predicate_op50_write_state4 = (~(next_state_load_reg_232_pp0_iter0_reg == 2'd1) & ~(next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_7_reg_260 == 1'd1) & (tmp_6_reg_248_pp0_iter0_reg == 1'd1) & (tmp_5_reg_279_pp0_iter0_reg == 1'd1) & (tmp_4_reg_244_pp0_iter0_reg == 1'd1) & (tmp_3_reg_240_pp0_iter0_reg == 1'd1) & (tmp_reg_236_pp0_iter0_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op51_write_state4 = (~(next_state_load_reg_232_pp0_iter0_reg == 2'd1) & ~(next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_7_reg_260 == 1'd1) & (tmp_6_reg_248_pp0_iter0_reg == 1'd1) & (tmp_5_reg_279_pp0_iter0_reg == 1'd1) & (tmp_4_reg_244_pp0_iter0_reg == 1'd1) & (tmp_3_reg_240_pp0_iter0_reg == 1'd1) & (tmp_reg_236_pp0_iter0_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op52_write_state5 = ((next_state_load_reg_232_pp0_iter0_reg == 2'd1) & (tmp_1_reg_252 == 1'd1));
end

always @ (*) begin
    ap_predicate_op55_write_state5 = ((next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_2_reg_256 == 1'd1));
end

always @ (*) begin
    ap_predicate_op56_write_state5 = ((next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_2_reg_256 == 1'd1));
end

always @ (*) begin
    ap_predicate_op59_write_state5 = (~(next_state_load_reg_232_pp0_iter0_reg == 2'd1) & ~(next_state_load_reg_232_pp0_iter0_reg == 2'd2) & (tmp_7_reg_260 == 1'd1) & (tmp_6_reg_248_pp0_iter0_reg == 1'd1) & (tmp_5_reg_279_pp0_iter0_reg == 1'd1) & (tmp_4_reg_244_pp0_iter0_reg == 1'd1) & (tmp_3_reg_240_pp0_iter0_reg == 1'd1) & (tmp_reg_236_pp0_iter0_reg == 1'd1));
end

assign grp_nbwritereq_fu_108_p3 = lbTxDataOut_TREADY_int_regslice;

assign grp_nbwritereq_fu_116_p3 = tagsOut_TREADY_int_regslice;

assign lbTxDataOut_TVALID = regslice_both_lbTxDataOut_U_vld_out;

assign lbTxLengthOut_TVALID = regslice_both_lbTxLengthOut_U_vld_out;

assign lbTxMetadataOut_TVALID = regslice_both_lbTxMetadataOut_U_vld_out;

assign metadata_from_book_TREADY = regslice_both_metadata_from_book_U_ack_in;

assign or_ln215_fu_221_p2 = (shl_ln_fu_213_p3 | 73'd4703919738795935662080);

assign order_from_book_TREADY = regslice_both_order_from_book_U_ack_in;

assign shl_ln_fu_213_p3 = {{second_packet_last}, {72'd0}};

assign tagsOut_TVALID = regslice_both_tagsOut_U_vld_out;

assign time_from_book_TREADY = regslice_both_time_from_book_U_ack_in;

assign tmp_3_nbreadreq_fu_84_p3 = time_from_book_TVALID_int_regslice;

assign tmp_4_nbreadreq_fu_92_p3 = order_from_book_TVALID_int_regslice;

assign tmp_nbreadreq_fu_76_p3 = metadata_from_book_TVALID_int_regslice;

assign zext_ln215_fu_227_p1 = or_ln215_fu_221_p2;

endmodule //Fast_processor_txPath
